import { describe, expect, it } from 'vitest'
import { mkdtempSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'
import ts from 'typescript'
import {
  generateRpcClientFiles,
  UnsupportedJsonSchemaError,
  type RpcSchema,
} from '../src/generate.js'

type FetchLike = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>

interface RpcClientForTests {
  call(method: string, params: unknown, options?: { signal?: AbortSignal; headers?: HeadersInit }): Promise<unknown>
  batch(
    items: readonly { method: string; params: unknown }[],
    options?: { signal?: AbortSignal; headers?: HeadersInit }
  ): Promise<readonly BatchItemResultForTests[]>
}

interface BatchItemResultForTests {
  ok: boolean
  result?: unknown
  error?: {
    code: number
    message: string
    data?: unknown
  }
}

interface TestSpan {
  headers?: HeadersInit
  setError(error: unknown): void
  end(): void
}

interface TestInstrumentation {
  startSpan(context: { methods: readonly string[]; batch: boolean }): TestSpan | undefined
}

interface GeneratedClientModule {
  createRpcApi(options: {
    url: string
    fetch?: FetchLike
    headers?: HeadersInit | ((context: { methods: readonly string[]; batch: boolean }) => HeadersInit | Promise<HeadersInit>)
    idGenerator?: () => string | number
    validateResults?: boolean
    transformResult?: (method: string, result: unknown) => unknown
    instrumentation?: TestInstrumentation
  }): RpcApiForTests
  createRpcClient(options: {
    url: string
    fetch?: FetchLike
    headers?: HeadersInit | ((context: { methods: readonly string[]; batch: boolean }) => HeadersInit | Promise<HeadersInit>)
    idGenerator?: () => string | number
    validateResults?: boolean
    transformResult?: (method: string, result: unknown) => unknown
    instrumentation?: TestInstrumentation
  }): RpcClientForTests
  RpcError: new (code: number, message: string, data?: unknown) => Error & { code: number; data?: unknown }
  RpcTransportError: new (status: number, statusText: string, body: string) => Error
  RpcProtocolError: new (message: string) => Error
}

interface RpcApiForTests {
  math: {
    add(params: unknown, options?: { signal?: AbortSignal; headers?: HeadersInit }): Promise<unknown>
  }
  user: {
    get(params: unknown, options?: { signal?: AbortSignal; headers?: HeadersInit }): Promise<unknown>
  }
  $request: {
    math: {
      add(params: unknown): { method: string; params: unknown }
    }
    user: {
      get(params: unknown): { method: string; params: unknown }
    }
  }
  $batch(
    items: readonly { method: string; params: unknown }[],
    options?: { signal?: AbortSignal; headers?: HeadersInit }
  ): Promise<readonly BatchItemResultForTests[]>
  $client: RpcClientForTests
}

describe('JSON-RPC client generator', () => {
  it('generates stable TypeScript and Zod output for common schema shapes', () => {
    const schema = {
      methods: {
        'z.second': {
          params: {
            type: 'object',
            properties: {
              id: { type: 'string', format: 'uuid' },
            },
            required: ['id'],
          },
          result: {
            type: 'object',
            properties: {
              ok: { type: 'boolean' },
            },
            required: ['ok'],
          },
        },
        'a.first': {
          params: {
            type: 'object',
            properties: {
              name: { type: 'string' },
              nickname: { type: ['string', 'null'] },
              tags: {
                type: 'array',
                items: { type: 'string' },
              },
              status: {
                enum: ['Open', 'Closed', null],
              },
            },
            required: ['name', 'nickname', 'tags', 'status'],
          },
          result: {
            type: 'object',
            properties: {
              count: { type: 'integer' },
              maybe: { type: ['number', 'null'] },
              state: { enum: ['Open', 'Closed', null] },
            },
            required: ['count', 'maybe', 'state'],
          },
        },
      },
    } satisfies RpcSchema

    const generated = generateRpcClientFiles(schema, {
      generatedBy: 'test-generator',
      sourceLabel: 'test-schema.json',
    })

    expect(generated.typesSource).toContain('// Auto-generated by test-generator')
    expect(generated.typesSource.indexOf('"a.first"')).toBeLessThan(
      generated.typesSource.indexOf('"z.second"')
    )
    expect(generated.typesSource).toContain('nickname: string | null | undefined')
    expect(generated.typesSource).toContain('tags: string[]')
    expect(generated.typesSource).toContain('status: ("Open" | "Closed") | null | undefined')
    expect(generated.schemasSource).toContain('maybe: z.number().nullish(),')
    expect(generated.schemasSource).toContain('state: z.enum(["Open", "Closed"]).nullish(),')
    expect(generated.clientSource).toContain("import type { RpcMethods } from './rpc-types.js'")
    expect(generated.clientSource).toContain("import { rpcResultSchemas } from './rpc-schemas.js'")
    expect(generated.clientSource).toContain('export interface RpcApi')
    expect(generated.clientSource).toContain('readonly "a": {')
    expect(generated.clientSource).toContain('readonly "first": RpcEndpoint<"a.first">')
    expect(generated.clientSource).toContain('export function createRpcClient')
    expect(generated.clientSource).toContain('export function createRpcApi')
  })

  it('strips top-level params and result nullability', () => {
    const schema = {
      methods: {
        'nullable.topLevel': {
          params: {
            type: ['object', 'null'],
            properties: {
              id: { type: 'string' },
            },
            required: ['id'],
          },
          result: {
            type: ['number', 'null'],
          },
        },
      },
    } satisfies RpcSchema

    const generated = generateRpcClientFiles(schema)

    expect(generated.typesSource).toContain('params: {')
    expect(generated.typesSource).toContain('result: number')
    expect(generated.typesSource).not.toContain('result: number | null | undefined')
    expect(generated.schemasSource).toContain('"nullable.topLevel": z.number(),')
  })

  it('resolves local JSON pointer references inside a method schema', () => {
    const schema = {
      methods: {
        'ea.summary': {
          params: {
            type: 'object',
            properties: {},
          },
          result: {
            type: 'object',
            properties: {
              incomeByCategory: {
                type: 'array',
                items: {
                  type: 'object',
                  properties: {
                    taxCategoryId: { type: 'string' },
                    netAmount: { type: 'number' },
                  },
                  required: ['taxCategoryId', 'netAmount'],
                },
              },
              expenseByCategory: {
                type: 'array',
                items: {
                  $ref: '#/properties/incomeByCategory/items',
                },
              },
            },
            required: ['incomeByCategory', 'expenseByCategory'],
          },
        },
      },
    } satisfies RpcSchema

    const generated = generateRpcClientFiles(schema)

    expect(generated.typesSource).toContain('expenseByCategory: {')
    expect(generated.typesSource).toContain('taxCategoryId: string')
    expect(generated.typesSource).not.toContain('expenseByCategory: unknown[]')
    expect(generated.schemasSource).toContain('expenseByCategory: z.array(z.object({')
  })

  it('fails fast for unsupported schema composition', () => {
    const schema = {
      methods: {
        'unsupported.oneOf': {
          params: { type: 'object', properties: {} },
          result: {
            oneOf: [{ type: 'string' }, { type: 'number' }],
          },
        },
      },
    } satisfies RpcSchema

    expect(() => generateRpcClientFiles(schema)).toThrow(UnsupportedJsonSchemaError)
  })

  it('generates a fetch client with headers, AbortSignal, result transform, and validation', async () => {
    const generated = generateRpcClientFiles(rpcClientTestSchema())
    const clientModule = await loadGeneratedClient(generated.clientSource)
    const abort = new AbortController()
    const seenContexts: Array<{ methods: readonly string[]; batch: boolean }> = []

    const fetchImpl: FetchLike = async (input, init) => {
      expect(input.toString()).toBe('https://example.test/rpc')
      expect(init?.method).toBe('POST')
      expect(init?.signal).toBe(abort.signal)

      const headers = new Headers(init?.headers)
      expect(headers.get('content-type')).toBe('application/json')
      expect(headers.get('authorization')).toBe('Bearer test')
      expect(headers.get('x-request')).toBe('single')

      const request = JSON.parse(String(init?.body)) as { id: string; method: string; params: unknown }
      expect(request).toMatchObject({
        id: 'request-1',
        method: 'math.add',
        params: { left: 1, right: 2 },
      })

      return jsonResponse({ jsonrpc: '2.0', id: request.id, result: '3' })
    }

    const rpc = clientModule.createRpcApi({
      url: 'https://example.test/rpc',
      fetch: fetchImpl,
      headers: (context) => {
        seenContexts.push(context)
        return { Authorization: 'Bearer test' }
      },
      idGenerator: () => 'request-1',
      transformResult: (method, result) => method === 'math.add' ? Number(result) : result,
    })

    await expect(
      rpc.math.add({ left: 1, right: 2 }, {
        signal: abort.signal,
        headers: { 'X-Request': 'single' },
      })
    ).resolves.toBe(3)
    expect(seenContexts).toEqual([{ methods: ['math.add'], batch: false }])
  })

  it('throws typed errors for transport and JSON-RPC failures', async () => {
    const generated = generateRpcClientFiles(rpcClientTestSchema())
    const clientModule = await loadGeneratedClient(generated.clientSource)

    const transportClient = clientModule.createRpcClient({
      url: 'https://example.test/rpc',
      fetch: async () => new Response('temporarily unavailable', {
        status: 503,
        statusText: 'Service Unavailable',
      }),
      idGenerator: () => 'request-1',
    })

    await expect(transportClient.call('math.add', { left: 1, right: 2 }))
      .rejects.toMatchObject({
        name: 'RpcTransportError',
        status: 503,
        body: 'temporarily unavailable',
      })

    const rpcClient = clientModule.createRpcClient({
      url: 'https://example.test/rpc',
      fetch: async () => jsonResponse({
        jsonrpc: '2.0',
        id: 'request-2',
        error: { code: -32602, message: 'Invalid params', data: { field: 'left' } },
      }),
      idGenerator: () => 'request-2',
    })

    await expect(rpcClient.call('math.add', { left: 1, right: 2 }))
      .rejects.toMatchObject({
        name: 'RpcError',
        code: -32602,
        data: { field: 'left' },
      })

    const mismatchedIdClient = clientModule.createRpcClient({
      url: 'https://example.test/rpc',
      fetch: async () => jsonResponse({ jsonrpc: '2.0', id: 'different-request', result: 3 }),
      idGenerator: () => 'request-3',
    })

    await expect(mismatchedIdClient.call('math.add', { left: 1, right: 2 }))
      .rejects.toMatchObject({
        name: 'RpcProtocolError',
        message: 'JSON-RPC response id does not match request id.',
      })
  })

  it('generates a batch client that preserves input order and per-item errors', async () => {
    const generated = generateRpcClientFiles(rpcClientTestSchema())
    const clientModule = await loadGeneratedClient(generated.clientSource)
    const expectedIds = ['request-1', 'request-2', 'request-3']
    const ids = [...expectedIds]
    const seenContexts: Array<{ methods: readonly string[]; batch: boolean }> = []

    const rpc = clientModule.createRpcApi({
      url: 'https://example.test/rpc',
      fetch: async (_input, init) => {
        const headers = new Headers(init?.headers)
        expect(headers.get('x-batch')).toBe('true')

        const requests = JSON.parse(String(init?.body)) as Array<{ id: string; method: string }>
        expect(requests.map((request) => request.id)).toEqual(expectedIds)
        expect(requests.map((request) => request.method)).toEqual(['math.add', 'user.get', 'math.add'])

        return jsonResponse([
          { jsonrpc: '2.0', id: 'request-2', error: { code: -32601, message: 'Method not found' } },
          { jsonrpc: '2.0', id: 'request-3', result: 'not a number' },
          { jsonrpc: '2.0', id: 'request-1', result: 3 },
        ])
      },
      headers: async (context) => {
        seenContexts.push(context)
        return { 'X-Batch': String(context.batch) }
      },
      idGenerator: () => ids.shift() ?? 'unexpected',
    })

    const results = await rpc.$batch([
      rpc.$request.math.add({ left: 1, right: 2 }),
      rpc.$request.user.get({ id: 'user-1' }),
      rpc.$request.math.add({ left: 3, right: 4 }),
    ] as const)

    expect(results[0]).toMatchObject({ ok: true, result: 3 })
    expect(results[1]).toMatchObject({ ok: false, error: { code: -32601 } })
    expect(results[2]).toMatchObject({ ok: false, error: { code: -32603 } })
    expect(seenContexts).toEqual([
      { methods: ['math.add', 'user.get', 'math.add'], batch: true },
    ])

    const duplicateIdClient = clientModule.createRpcApi({
      url: 'https://example.test/rpc',
      fetch: async () => jsonResponse([
        { jsonrpc: '2.0', id: 'request-1', result: 3 },
        { jsonrpc: '2.0', id: 'request-1', result: 7 },
      ]),
      idGenerator: () => 'request-1',
    })

    await expect(duplicateIdClient.$batch([
      duplicateIdClient.$request.math.add({ left: 1, right: 2 }),
      duplicateIdClient.$request.math.add({ left: 3, right: 4 }),
    ] as const)).rejects.toMatchObject({
      name: 'RpcProtocolError',
      message: 'JSON-RPC batch response contains a duplicate id.',
    })
  })

  it('drives the instrumentation hook for single calls, injecting headers and recording outcome', async () => {
    const generated = generateRpcClientFiles(rpcClientTestSchema())
    const clientModule = await loadGeneratedClient(generated.clientSource)

    const events: string[] = []
    const seenContexts: Array<{ methods: readonly string[]; batch: boolean }> = []
    let seenTraceparent: string | null = null

    const instrumentation: TestInstrumentation = {
      startSpan(context) {
        seenContexts.push(context)
        events.push('start')
        return {
          headers: { traceparent: '00-trace-span-01' },
          setError() {
            events.push('error')
          },
          end() {
            events.push('end')
          },
        }
      },
    }

    const okClient = clientModule.createRpcClient({
      url: 'https://example.test/rpc',
      fetch: async (_input, init) => {
        seenTraceparent = new Headers(init?.headers).get('traceparent')
        return jsonResponse({ jsonrpc: '2.0', id: 'request-1', result: 3 })
      },
      idGenerator: () => 'request-1',
      instrumentation,
    })

    await expect(okClient.call('math.add', { left: 1, right: 2 })).resolves.toBe(3)
    expect(seenTraceparent).toBe('00-trace-span-01')
    expect(seenContexts).toEqual([{ methods: ['math.add'], batch: false }])
    expect(events).toEqual(['start', 'end'])

    events.length = 0
    const errorClient = clientModule.createRpcClient({
      url: 'https://example.test/rpc',
      fetch: async () => jsonResponse({
        jsonrpc: '2.0',
        id: 'request-2',
        error: { code: -32602, message: 'Invalid params' },
      }),
      idGenerator: () => 'request-2',
      instrumentation,
    })

    await expect(errorClient.call('math.add', { left: 1, right: 2 }))
      .rejects.toMatchObject({ name: 'RpcError', code: -32602 })
    expect(events).toEqual(['start', 'error', 'end'])
  })

  it('starts one span per batch and treats per-item errors as data, not span failures', async () => {
    const generated = generateRpcClientFiles(rpcClientTestSchema())
    const clientModule = await loadGeneratedClient(generated.clientSource)

    const events: string[] = []
    const ids = ['request-1', 'request-2']

    const rpc = clientModule.createRpcApi({
      url: 'https://example.test/rpc',
      fetch: async () => jsonResponse([
        { jsonrpc: '2.0', id: 'request-1', result: 3 },
        { jsonrpc: '2.0', id: 'request-2', error: { code: -32601, message: 'Method not found' } },
      ]),
      idGenerator: () => ids.shift() ?? 'unexpected',
      instrumentation: {
        startSpan(context) {
          events.push(`start:${context.batch}:${context.methods.length}`)
          return {
            setError() {
              events.push('error')
            },
            end() {
              events.push('end')
            },
          }
        },
      },
    })

    const results = await rpc.$batch([
      rpc.$request.math.add({ left: 1, right: 2 }),
      rpc.$request.math.add({ left: 3, right: 4 }),
    ] as const)

    expect(results[0]).toMatchObject({ ok: true, result: 3 })
    expect(results[1]).toMatchObject({ ok: false, error: { code: -32601 } })
    expect(events).toEqual(['start:true:2', 'end'])
  })

  it('attaches an idempotency key to idempotent operations by default, and honors overrides', async () => {
    const metaKey = 'dev.wimmesberger.elarion/idempotencyKey'
    const schema = rpcClientTestSchema()
    schema.methods['math.add'].idempotent = true

    const generated = generateRpcClientFiles(schema)
    expect(generated.clientSource).toContain('rpcIdempotentMethods')
    expect(generated.clientSource).toContain(metaKey)

    const clientModule = await loadGeneratedClient(generated.clientSource)
    const bodies: Array<{ method: string; params: Record<string, unknown> }> = []
    const fetchImpl: FetchLike = async (_input, init) => {
      const request = JSON.parse(String(init?.body))
      const items = Array.isArray(request) ? request : [request]
      for (const item of items) bodies.push(item)
      const respond = (item: { id: string; method: string }) =>
        ({ jsonrpc: '2.0', id: item.id, result: item.method === 'math.add' ? 3 : { id: 'u', name: 'n' } })
      return jsonResponse(Array.isArray(request) ? request.map(respond) : respond(request))
    }

    const meta = (index: number) => bodies[index].params._meta as Record<string, string> | undefined

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const rpc = clientModule.createRpcApi({ url: 'https://example.test/rpc', fetch: fetchImpl }) as any

    await rpc.math.add({ left: 1, right: 2 })
    expect(meta(0)?.[metaKey]).toEqual(expect.any(String))
    expect((meta(0)?.[metaKey] ?? '').length).toBeGreaterThan(0)

    // A non-idempotent operation never gets a key.
    await rpc.user.get({ id: 'x' })
    expect(meta(1)).toBeUndefined()

    // A caller-supplied key (stable across a retry layer's retries) is used verbatim.
    await rpc.math.add({ left: 1, right: 2 }, { idempotencyKey: 'fixed-key' })
    expect(meta(2)?.[metaKey]).toBe('fixed-key')

    // `false` disables the key for a single call.
    await rpc.math.add({ left: 1, right: 2 }, { idempotencyKey: false })
    expect(meta(3)).toBeUndefined()

    // Each batch item gets its own key (batch-correct, per-call granularity).
    await rpc.$batch([rpc.$request.math.add({ left: 1, right: 2 }), rpc.$request.math.add({ left: 3, right: 4 })] as const)
    expect(meta(4)?.[metaKey]).toEqual(expect.any(String))
    expect(meta(5)?.[metaKey]).toEqual(expect.any(String))
    expect(meta(4)?.[metaKey]).not.toBe(meta(5)?.[metaKey])

    // Globally disabling opts every operation out.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const off = clientModule.createRpcApi({ url: 'https://example.test/rpc', fetch: fetchImpl, idempotency: { enabled: false } }) as any
    await off.math.add({ left: 1, right: 2 })
    expect(meta(6)).toBeUndefined()
  })
})

function rpcClientTestSchema(): RpcSchema {
  return {
    methods: {
      'math.add': {
        params: {
          type: 'object',
          properties: {
            left: { type: 'number' },
            right: { type: 'number' },
          },
          required: ['left', 'right'],
        },
        result: { type: 'number' },
      },
      'user.get': {
        params: {
          type: 'object',
          properties: {
            id: { type: 'string' },
          },
          required: ['id'],
        },
        result: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            name: { type: 'string' },
          },
          required: ['id', 'name'],
        },
      },
    },
  }
}

async function loadGeneratedClient(clientSource: string): Promise<GeneratedClientModule> {
  const dir = mkdtempSync(join(tmpdir(), 'elarion-rpc-client-'))
  const jsSource = ts.transpileModule(clientSource, {
    compilerOptions: {
      module: ts.ModuleKind.ES2022,
      target: ts.ScriptTarget.ES2022,
    },
  }).outputText

  writeFileSync(join(dir, 'rpc-client.mjs'), jsSource, 'utf-8')
  writeFileSync(join(dir, 'rpc-schemas.js'), [
    'function numberSchema() {',
    '  return {',
    '    parse(value) {',
    "      if (typeof value !== 'number') throw new Error('Expected number')",
    '      return value',
    '    }',
    '  }',
    '}',
    '',
    'function userSchema() {',
    '  return {',
    '    parse(value) {',
    "      if (typeof value !== 'object' || value === null || Array.isArray(value)) throw new Error('Expected object')",
    '      return value',
    '    }',
    '  }',
    '}',
    '',
    'export const rpcResultSchemas = {',
    "  'math.add': numberSchema(),",
    "  'user.get': userSchema(),",
    '}',
    '',
  ].join('\n'), 'utf-8')

  return await import(pathToFileURL(join(dir, 'rpc-client.mjs')).href) as GeneratedClientModule
}

function jsonResponse(body: unknown): Response {
  return new Response(JSON.stringify(body), {
    status: 200,
    headers: { 'Content-Type': 'application/json' },
  })
}
