namespace Elarion.Devices;

/// <summary>
/// Durable per-device symmetric key material: device id → key. The write side is owned by
/// provisioning (<see cref="IDevicePairingService.RedeemAsync"/> mints and stores the key); the
/// read side is the connect-time authenticator (<see cref="HmacChallengeVerifier"/>). Key material
/// is raw symmetric bytes — the self-hosted trade-off is that the server can recompute MACs, which
/// is accepted and documented (ADR-0054).
/// </summary>
public interface IDeviceKeyStore {
    /// <summary>The key for <paramref name="deviceId"/>, or <see langword="null"/> when the device is unknown.</summary>
    /// <param name="deviceId">The device id.</param>
    /// <param name="cancellationToken">Cancels the lookup.</param>
    ValueTask<ReadOnlyMemory<byte>?> GetKeyAsync(string deviceId, CancellationToken cancellationToken = default);

    /// <summary>
    /// Stores the key for <paramref name="deviceId"/>, replacing any existing key. Replacement is
    /// deliberate: a pairing code issued for an already-provisioned device id <b>is</b> the re-key
    /// authorization (device reset, lost key), so redeem rotates rather than failing after the
    /// code was already consumed.
    /// </summary>
    /// <param name="deviceId">The device id.</param>
    /// <param name="key">The key material (CSPRNG-generated by the caller).</param>
    /// <param name="cancellationToken">Cancels the write.</param>
    ValueTask PutAsync(string deviceId, ReadOnlyMemory<byte> key, CancellationToken cancellationToken = default);

    /// <summary>
    /// Deletes the device's key (revocation: the device can no longer authenticate).
    /// Returns whether a key existed.
    /// </summary>
    /// <param name="deviceId">The device id.</param>
    /// <param name="cancellationToken">Cancels the delete.</param>
    ValueTask<bool> RemoveAsync(string deviceId, CancellationToken cancellationToken = default);
}
