using System.Collections.Immutable;
using System.Text;
using Elarion.Generators;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Elarion.EntityFrameworkCore.Generators;

/// <summary>
/// Implements the EF generator's per-feature model-configuration seam for every partial <c>DbContext</c>
/// annotated with <c>[GenerateElarionTenantScoping]</c>, so the tenant query filter is attached to every
/// tenant-scoped entity without the host writing model code.
/// </summary>
/// <remarks>
/// The emitted call is deliberately thin: which entities are tenant-scoped is decided at model-build time from
/// the model itself, so entities discovered through navigations — and entities other configuration seams added
/// — are covered too. Deciding it here instead would mean this generator re-deriving EF's own entity
/// discovery, and silently missing whatever it got wrong.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class ElarionTenantScopingGenerator : IIncrementalGenerator {
    private const string AttributeMetadataName = "Elarion.EntityFrameworkCore.GenerateElarionTenantScopingAttribute";
    private const string GenerateDbSetsAttributeName = ElarionGeneratorConventions.GenerateDbSetsAttribute;
    private const string TenancyNamespace = "global::Elarion.EntityFrameworkCore.MultiTenancy";

    // The per-feature seam DbContextGenerator declares for this attribute — both sides derive the name from the
    // same convention, so they cannot drift.
    private static readonly string SeamMethodName =
        ElarionGeneratorConventions.ModelConfigurationSeamName("GenerateElarionTenantScopingAttribute");

    private static readonly DiagnosticDescriptor MissingGenerateDbSets = new(
        "ELTEN001",
        "[GenerateElarionTenantScoping] requires [GenerateDbSets]",
        "Context '{0}' is annotated with [GenerateElarionTenantScoping] but not [GenerateDbSets]; add "
        + "[GenerateDbSets] so the model-configuration seam that applies the tenant filter is generated",
        "Elarion.EntityFrameworkCore",
        DiagnosticSeverity.Error,
        true);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var targets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeMetadataName,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => GetTarget(ctx))
            .Where(static target => target is not null)
            .WithTrackingName("TenantScopingTargets");

        context.RegisterSourceOutput(targets, static (spc, target) => {
            if (target is null) return;

            foreach (var diagnostic in target.Diagnostics) spc.ReportDiagnostic(diagnostic.ToDiagnostic());

            if (target.Emit) Emit(spc, target);
        });
    }

    private sealed record TenantScopingTarget(
        string Namespace,
        string ContextName,
        string HintName,
        bool Emit,
        EquatableArray<DiagnosticInfo> Diagnostics);

    private static TenantScopingTarget? GetTarget(GeneratorAttributeSyntaxContext ctx) {
        if (ctx.TargetSymbol is not INamedTypeSymbol contextSymbol) return null;

        var ns = contextSymbol.ContainingNamespace is { IsGlobalNamespace: false } containing
            ? containing.ToDisplayString()
            : "";
        var contextName = contextSymbol.Name;
        var hintName = (ns.Length == 0 ? contextName : ns + "." + contextName).Replace('.', '_');

        var hasGenerateDbSets = contextSymbol.GetAttributes()
            .Any(attribute => attribute.AttributeClass?.ToDisplayString() == GenerateDbSetsAttributeName);

        var diagnostics = ImmutableArray.CreateBuilder<DiagnosticInfo>();
        if (!hasGenerateDbSets)
            diagnostics.Add(DiagnosticInfo.Create(
                MissingGenerateDbSets,
                LocationInfo.From(contextSymbol),
                contextSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));

        return new TenantScopingTarget(ns, contextName, hintName, hasGenerateDbSets, diagnostics.ToImmutable());
    }

    private static void Emit(SourceProductionContext spc, TenantScopingTarget target) {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Source: Elarion.EntityFrameworkCore.Generators.ElarionTenantScopingGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine(
            "#pragma warning disable CS1591 // Generated code is not documented; a consuming project that enables GenerateDocumentationFile must not be warned about it.");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        if (target.Namespace.Length > 0) {
            sb.AppendLine($"namespace {target.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {target.ContextName}");
        sb.AppendLine("{");
        sb.AppendLine(
            "    // Implements the per-feature model-configuration seam the EF DbContext generator calls at the");
        sb.AppendLine(
            "    // end of ConfigureEntities — last, so it also covers entities the other seams added and the");
        sb.AppendLine("    // children EF discovered through navigations.");
        sb.AppendLine($"    partial void {SeamMethodName}(ModelBuilder modelBuilder) =>");
        sb.AppendLine(
            $"        {TenancyNamespace}.ElarionTenantScopingModelBuilderExtensions.ApplyElarionTenantScoping(");
        sb.AppendLine("            modelBuilder, this);");
        sb.AppendLine("}");

        spc.AddSource($"{target.HintName}.ElarionTenantScoping.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
