using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Elarion.EntityFrameworkCore.Generators;

/// <summary>
/// Emits the compact assembly-level <c>[EntityConfiguration]</c> manifest for the current compilation so a
/// <c>[GenerateDbSets]</c> <c>DbContext</c> in <em>another</em> assembly can discover those configurations from
/// the reference instead of scanning its symbol tree (see <see cref="DbContextGenerator"/>'s cross-assembly read).
/// </summary>
/// <remarks>
/// This emitter is deliberately separate from <see cref="DbContextGenerator"/>. The DbSet generator emits only
/// members onto a partial class — output that IDE generator hosts refresh reliably — and no longer also mutates
/// the compilation's assembly attributes. Mirrors the
/// <see cref="Elarion.Generators.ElarionManifestGenerator"/> / <c>AppModuleDiscoveryGenerator</c> emit/consume
/// split on the runtime side. The discovery itself is shared with the DbSet generator via
/// <see cref="EntityConfigurationDiscovery"/>; only valid configurations are emitted here (the misuse warning
/// <c>ELEFC001</c> is reported solely by <see cref="DbContextGenerator"/>, so it is never duplicated).
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class EntityConfigurationManifestGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var configs = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                EntityConfigurationDiscovery.AttributeName,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, ct) => EntityConfigurationDiscovery.CreateConfig(ctx, ct))
            .Where(static result => result.Config is not null)
            .Select(static (result, _) => result.Config!.Value)
            .Collect()
            .WithTrackingName("ManifestConfigs");

        context.RegisterSourceOutput(configs, static (spc, source) => EmitManifest(spc, source));
    }

    private static void EmitManifest(SourceProductionContext spc, ImmutableArray<ConfigInfo> configs)
    {
        if (configs.IsEmpty)
        {
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Source: Elarion.EntityFrameworkCore.Generators.EntityConfigurationManifestGenerator");
        sb.AppendLine("// Do not edit this file manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        foreach (var config in configs.OrderBy(static c => c.FullName, StringComparer.Ordinal))
        {
            var entities = config.Entities.AsImmutableArray
                .Select(static e => (e.Name, e.FullName, e.Namespace))
                .ToList();
            AppendAssemblyMetadata(
                sb,
                EntityConfigurationManifest.ConfigKey,
                EntityConfigurationManifest.EncodeConfig(
                    config.FullName,
                    config.Namespace,
                    config.Scopes.AsImmutableArray,
                    entities));
        }

        spc.AddSource("ElarionEntityConfigurationManifest.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void AppendAssemblyMetadata(StringBuilder sb, string key, string value)
    {
        sb.Append("[assembly: global::System.Reflection.AssemblyMetadataAttribute(");
        sb.Append(SymbolDisplay.FormatLiteral(key, quote: true));
        sb.Append(", ");
        sb.Append(SymbolDisplay.FormatLiteral(value, quote: true));
        sb.AppendLine(")]");
    }
}
