using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Elarion.Generators;

public sealed partial class HandlerRegistrationGenerator {
    private static void EmitModuleAggregations(
        SourceProductionContext spc,
        ImmutableArray<HandlerInfo> handlers,
        Compilation compilation) {
        if (!FrameworkFeatureTriggers.HasAssemblyTrigger(compilation, TriggerAttributeMetadataName))
            return;

        var moduleAttrSymbol = compilation.GetTypeByMetadataName(AppModuleAttributeMetadataName);
        if (moduleAttrSymbol is null)
            return;

        var modules = DiscoverModules(compilation, moduleAttrSymbol);
        var moduleHandlers = GroupHandlersByModule(handlers, modules);

        foreach (var kvp in moduleHandlers.OrderBy(x => x.Key.Name, StringComparer.Ordinal)) {
            var code = GenerateModuleAggregation(kvp.Key, kvp.Value);
            spc.AddSource($"{kvp.Key.Name}HandlerExtensions.g.cs", SourceText.From(code, Encoding.UTF8));

            if (kvp.Value.Count == 0)
                continue;

            var module = kvp.Key;
            var nsPrefix = module.Namespace.Length > 0 ? $"global::{module.Namespace}." : "global::";
            ModuleDefaultsEmitter.EmitFiller(
                spc,
                module.Namespace,
                module.TypeName,
                ModuleDefaultsEmitter.AddHandlersMethod,
                "Handlers",
                $"{nsPrefix}{module.Name}HandlerExtensions.Add{module.Name}Handlers(services);");
        }
    }

    private static ImmutableArray<ModuleInfo> DiscoverModules(
        Compilation compilation,
        INamedTypeSymbol moduleAttrSymbol) {
        var modules = ImmutableArray.CreateBuilder<ModuleInfo>();

        foreach (var syntaxTree in compilation.SyntaxTrees) {
            var semanticModel = compilation.GetSemanticModel(syntaxTree);
            var root = syntaxTree.GetRoot();

            foreach (var typeDecl in root.DescendantNodes().OfType<TypeDeclarationSyntax>()) {
                if (semanticModel.GetDeclaredSymbol(typeDecl) is not INamedTypeSymbol typeSymbol)
                    continue;

                var moduleAttr = typeSymbol.GetAttributes()
                    .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, moduleAttrSymbol));
                if (moduleAttr is null)
                    continue;

                if (moduleAttr.ConstructorArguments.Length == 0 ||
                    moduleAttr.ConstructorArguments[0].Value is not string moduleName) {
                    continue;
                }

                var ns = typeSymbol.ContainingNamespace is { IsGlobalNamespace: false } containing
                    ? containing.ToDisplayString()
                    : "";
                modules.Add(new ModuleInfo(moduleName, ns, typeSymbol.Name));
            }
        }

        return modules.ToImmutable();
    }

    private static Dictionary<ModuleInfo, List<HandlerInfo>> GroupHandlersByModule(
        ImmutableArray<HandlerInfo> handlers,
        ImmutableArray<ModuleInfo> modules) {
        var moduleHandlers = modules.ToDictionary(module => module, _ => new List<HandlerInfo>());

        foreach (var handler in handlers) {
            var bestMatch = FindBestModule(handler, modules);
            if (bestMatch is not null)
                moduleHandlers[bestMatch].Add(handler);
        }

        return moduleHandlers;
    }

    private static ModuleInfo? FindBestModule(HandlerInfo handler, ImmutableArray<ModuleInfo> modules) {
        ModuleInfo? bestMatch = null;
        foreach (var module in modules) {
            if (!IsNamespaceInScope(handler.Namespace, module.Namespace))
                continue;

            if (bestMatch is null || module.Namespace.Length > bestMatch.Namespace.Length)
                bestMatch = module;
        }

        return bestMatch;
    }

    private static string GenerateModuleAggregation(ModuleInfo module, List<HandlerInfo> handlers) {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Source: Elarion.Generators.HandlerRegistrationGenerator (module aggregation)");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"namespace {module.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {module.Name}HandlerExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    public static IServiceCollection Add{module.Name}Handlers(");
        sb.AppendLine("        this IServiceCollection services,");
        sb.AppendLine("        ServiceLifetime lifetime = ServiceLifetime.Scoped)");
        sb.AppendLine("    {");

        foreach (var handler in handlers.OrderBy(x => x.HandlerName))
            sb.AppendLine($"        {handler.Namespace}.{handler.HandlerName}Registration.Add{handler.HandlerName}(services, lifetime);");

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}

