using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Elarion.Generators;

public sealed partial class HandlerRegistrationGenerator {
    private static void EmitModuleAggregations(
        SourceProductionContext spc,
        EquatableArray<HandlerInfo> handlers,
        EquatableArray<ModuleScanner.Module> modules) {
        var moduleHandlers = GroupHandlersByModule(handlers, modules);

        foreach (var kvp in moduleHandlers.OrderBy(x => x.Key.Name, StringComparer.Ordinal)) {
            var code = GenerateModuleAggregation(kvp.Key, kvp.Value);
            spc.AddSource($"{kvp.Key.Name}HandlerExtensions.g.cs", SourceText.From(code, Encoding.UTF8));

            if (kvp.Value.Count == 0)
                continue;

            var module = kvp.Key;
            var nsPrefix = module.Namespace.Length > 0 ? $"global::{module.Namespace}." : "global::";
            ModuleDefaultsEmitter.EmitFiller(
                spc,
                module.Namespace,
                module.TypeName,
                ModuleDefaultsEmitter.AddHandlersMethod,
                "Handlers",
                $"{nsPrefix}{module.Name}HandlerExtensions.Add{module.Name}Handlers(services);");
        }
    }

    private static Dictionary<ModuleScanner.Module, List<HandlerInfo>> GroupHandlersByModule(
        EquatableArray<HandlerInfo> handlers,
        EquatableArray<ModuleScanner.Module> modules) {
        var moduleHandlers = modules.ToDictionary(module => module, _ => new List<HandlerInfo>());

        foreach (var handler in handlers) {
            var bestMatch = FindBestModule(handler, modules);
            if (bestMatch is not null)
                moduleHandlers[bestMatch].Add(handler);
        }

        return moduleHandlers;
    }

    private static ModuleScanner.Module? FindBestModule(HandlerInfo handler,
        EquatableArray<ModuleScanner.Module> modules) {
        ModuleScanner.Module? bestMatch = null;
        foreach (var module in modules) {
            if (!ModuleScanner.IsInScope(handler.Namespace, module.Namespace))
                continue;

            if (bestMatch is null || module.Namespace.Length > bestMatch.Namespace.Length)
                bestMatch = module;
        }

        return bestMatch;
    }

    private static string GenerateModuleAggregation(ModuleScanner.Module module, List<HandlerInfo> handlers) {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Source: Elarion.Generators.HandlerRegistrationGenerator (module aggregation)");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"namespace {module.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {module.Name}HandlerExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    public static IServiceCollection Add{module.Name}Handlers(");
        sb.AppendLine("        this IServiceCollection services)");
        sb.AppendLine("    {");

        // No lifetime parameter: [Handler(Scope = …)] on each handler is the single source of truth
        // (ADR-0066) — a caller-supplied lifetime could silently defeat the ELSG011-013 verification.
        foreach (var handler in handlers.OrderBy(x => x.HandlerName, StringComparer.Ordinal))
            sb.AppendLine(
                $"        {handler.Namespace}.{handler.HandlerName}Registration.Add{handler.HandlerName}(services);");

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
