using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Elarion.Generators;

public sealed partial class HandlerRegistrationGenerator {
    private static void EmitHandlerRegistration(SourceProductionContext spc, HandlerInfo handler) {
        foreach (var diagnostic in handler.Diagnostics) {
            spc.ReportDiagnostic(diagnostic.ToDiagnostic());
        }

        var code = GenerateRegistration(handler);
        spc.AddSource(GenerateHandlerHintName(handler), SourceText.From(code, Encoding.UTF8));
    }

    private static string GenerateHandlerHintName(HandlerInfo handler) {
        var hintName = handler.HandlerFqn
            .Replace("global::", "")
            .Replace(".", "_")
            .Replace("<", "_")
            .Replace(">", "_")
            .Replace(",", "_")
            .Replace(" ", "");

        return $"{hintName}.g.cs";
    }

    private static string GenerateRegistration(HandlerInfo handler) {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Source: Elarion.Generators.HandlerRegistrationGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"namespace {handler.Namespace};");
        sb.AppendLine();

        sb.AppendLine($"public static class {handler.HandlerName}Registration");
        sb.AppendLine("{");
        // The metadata field is emitted before the AppliesTo fields so an `AppliesTo(HandlerMetadata)` field
        // initializer (which references __handlerMetadata) sees it initialized — static initializers run in order.
        AppendHandlerMetadataField(sb, handler);
        AppendAppliesToFields(sb, handler);
        AppendResourceBindingsField(sb, handler);
        AppendRegistrationMethod(sb, handler);
        AppendBuildPipelineMethods(sb, handler);

        if (handler.Cacheable is not null)
            AppendCachePolicy(sb, handler);

        if (handler.CacheInvalidation is not null)
            AppendCacheInvalidationPolicy(sb, handler);

        if (handler.Idempotent is not null)
            AppendIdempotencyPolicy(sb, handler);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AppendAppliesToFields(StringBuilder sb, HandlerInfo handler) {
        // A decorator with a `public static bool AppliesTo(HandlerMetadata)` predicate is attached conditionally.
        // The predicate is called once here (per closed handler type, at type init) and cached; the factory below
        // reads the cached bool. The call site is a direct static invocation, so it stays AOT/trim-safe.
        for (var i = 0; i < handler.Decorators.Length; i++) {
            var decorator = handler.Decorators[i];
            if (!decorator.HasAppliesTo)
                continue;

            // The single predicate form is `AppliesTo(HandlerMetadata)`; pass the cached metadata singleton.
            sb.AppendLine($"    private static readonly bool __pipelineApplies{i} =");
            sb.AppendLine($"        {decorator.DecoratorFqn}.AppliesTo(__handlerMetadata);");
        }
    }

    private static void AppendHandlerMetadataField(StringBuilder sb, HandlerInfo handler) {
        // Only emit the metadata singleton when a pipeline decorator actually asks for it (or the auto-attached
        // authorization decorator needs it). It captures the concrete handler type so an attribute-reading
        // decorator sees the true handler regardless of its position in the chain (the inner.GetType() approach
        // only works when innermost — a fail-open footgun).
        var wantsMetadata = handler.HasAuthorization || handler.HasFeatureGates;
        foreach (var dec in handler.Decorators) {
            // An `AppliesTo(HandlerMetadata)` predicate or a constructor HandlerMetadata dependency both need it.
            if (dec.HasAppliesTo) {
                wantsMetadata = true;
                break;
            }

            foreach (var dep in dec.ExtraDependencies) {
                if (dep.IsHandlerMetadata) {
                    wantsMetadata = true;
                    break;
                }
            }

            if (wantsMetadata)
                break;
        }

        if (!wantsMetadata)
            return;

        sb.AppendLine("    private static readonly global::Elarion.Abstractions.Pipeline.HandlerMetadata __handlerMetadata =");
        sb.AppendLine($"        new(typeof({handler.HandlerFqn}), typeof({handler.RequestFqn}), typeof({handler.ResponseFqn}));");
    }

    private static void AppendRegistrationMethod(StringBuilder sb, HandlerInfo handler) {
        sb.AppendLine($"    public static IServiceCollection Add{handler.HandlerName}(");
        sb.AppendLine("        this IServiceCollection services,");
        sb.AppendLine("        ServiceLifetime lifetime = ServiceLifetime.Scoped)");
        sb.AppendLine("    {");

        // Every handler is registered through the decorator factory because tracing is applied
        // unconditionally as the outermost decorator. The handler span is a no-op until a host
        // registers the Elarion.Handlers source, so there is no plain (undecorated) fast path.
        AppendDecoratedRegistration(sb, handler);

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
    }

    private static void AppendDecoratedRegistration(StringBuilder sb, HandlerInfo handler) {
        sb.AppendLine($"        services.Add(new ServiceDescriptor(typeof({handler.HandlerFqn}), typeof({handler.HandlerFqn}), lifetime));");
        sb.AppendLine("        services.Add(new ServiceDescriptor(");
        sb.AppendLine($"            typeof(global::Elarion.Abstractions.IHandler<{handler.RequestFqn}, {handler.ResponseFqn}>),");

        if (handler.VariantContractDeps.IsEmpty) {
            // Normal case: the synchronous pipeline factory builds the decorator chain per resolution.
            sb.AppendLine("            sp => BuildPipeline(sp),");
        } else {
            // The handler depends on a feature-flag variant, which is resolved asynchronously (per user). Register
            // the async-resolving proxy that awaits the variant builder on first dispatch instead of building
            // synchronously; everything else stays the same shared pipeline factory.
            sb.AppendLine(
                $"            sp => new global::Elarion.Abstractions.Pipeline.AsyncResolvedHandler<{handler.RequestFqn}, {handler.ResponseFqn}>(sp, BuildPipelineAsync),");
        }

        sb.AppendLine("            lifetime));");
    }

    // The shared pipeline factory: builds the decorator chain once per resolution, preserving normal scoped
    // lifetimes (Note 57). The normal registration calls it synchronously; a variant handler's async builder calls
    // the same method after awaiting its variant dependencies, so the chain is defined exactly once.
    private static void AppendBuildPipelineMethods(StringBuilder sb, HandlerInfo handler) {
        var ifaceFqn = $"global::Elarion.Abstractions.IHandler<{handler.RequestFqn}, {handler.ResponseFqn}>";

        sb.AppendLine($"    private static {ifaceFqn} BuildPipeline(global::System.IServiceProvider sp)");
        sb.AppendLine("    {");
        sb.AppendLine($"                {ifaceFqn} handler =");
        sb.AppendLine($"                    sp.GetRequiredService<{handler.HandlerFqn}>();");

        AppendCacheDecorator(sb, handler);
        AppendPipelineDecorators(sb, handler.Decorators);
        // Idempotency owns the unit-of-work transaction for [Idempotent] commands, so it wraps the handler and
        // the inner custom decorators — inside resilience/cache-invalidation/feature-gate/authorization (a
        // denied/gated/replayed request never claims a key) and outside the handler's own work.
        AppendIdempotencyDecorator(sb, handler);
        AppendResilienceDecorator(sb, handler);
        AppendCacheInvalidationDecorator(sb, handler);
        // The feature gate sits just inside authorization: a disabled feature never touches caching, the pipeline,
        // or the handler, but authorization still runs first so an unauthenticated caller is never told whether a
        // gated feature exists.
        AppendFeatureGateDecorator(sb, handler);
        // Authorization is the outermost functional gate (just inside tracing): a denied request never touches
        // caching, the pipeline (validation/transaction), or the handler, yet the denial is still traced.
        AppendAuthorizationDecorator(sb, handler);
        // Note: tracing is emitted last so the handler span is the outermost decorator and parents
        // any cache/resilience/pipeline child spans.
        AppendTracingDecorator(sb, handler);

        sb.AppendLine("                return handler;");
        sb.AppendLine("    }");

        if (handler.VariantContractDeps.IsEmpty)
            return;

        // The asynchronous builder: await-resolve each variant the handler depends on into the scoped cache (so the
        // transparent unkeyed registration reads the right implementation), then build the same pipeline.
        sb.AppendLine($"    private static async global::System.Threading.Tasks.ValueTask<{ifaceFqn}> BuildPipelineAsync(");
        sb.AppendLine("        global::System.IServiceProvider sp,");
        sb.AppendLine("        global::System.Threading.CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine(
            "        var __variantCache = sp.GetRequiredService<global::Elarion.Abstractions.Features.VariantResolutionCache>();");
        foreach (var contractFqn in handler.VariantContractDeps.AsImmutableArray) {
            sb.AppendLine($"        await __variantCache.WarmAsync<{contractFqn}>(sp, ct).ConfigureAwait(false);");
        }

        sb.AppendLine("        return BuildPipeline(sp);");
        sb.AppendLine("    }");
    }

    private static void AppendCacheDecorator(StringBuilder sb, HandlerInfo handler) {
        if (handler.Cacheable is null)
            return;

        sb.AppendLine($"                handler = new global::Elarion.Abstractions.Caching.CacheDecorator<{handler.RequestFqn}, {handler.ResponseFqn}>(");
        sb.AppendLine("                    handler,");
        sb.AppendLine("                    sp.GetRequiredService<global::Elarion.Abstractions.Caching.IHandlerCache>(),");
        sb.AppendLine($"                    new {handler.HandlerName}CachePolicy());");
    }

    private static void AppendPipelineDecorators(StringBuilder sb, ImmutableArray<DecoratorInfo> decorators) {
        for (var i = decorators.Length - 1; i >= 0; i--) {
            var dec = decorators[i];
            // Note 58: Decorators are emitted in reverse so the first configured decorator becomes the outermost wrapper.
            var indent = "                ";
            if (dec.HasAppliesTo) {
                // Attach only when the decorator's AppliesTo(HandlerMetadata) predicate returned true (cached above).
                sb.AppendLine($"{indent}if (__pipelineApplies{i})");
                indent += "    ";
            }

            sb.Append($"{indent}handler = new {dec.DecoratorFqn}(handler");
            foreach (var dep in dec.ExtraDependencies) {
                sb.Append(dep.IsHandlerMetadata
                    ? ", __handlerMetadata"
                    : $", sp.GetRequiredService<{dep.Fqn}>()");
            }
            sb.AppendLine(");");
        }
    }

    private static void AppendResilienceDecorator(StringBuilder sb, HandlerInfo handler) {
        if (handler.ResiliencePolicyName is null)
            return;

        sb.AppendLine($"                handler = new global::Elarion.Abstractions.Resilience.ResilienceDecorator<{handler.RequestFqn}, {handler.ResponseFqn}>(");
        sb.AppendLine("                    handler,");
        sb.AppendLine("                    sp.GetRequiredService<global::Elarion.Abstractions.Resilience.IResiliencePipelineRunner>(),");
        sb.AppendLine($"                    new global::Elarion.Abstractions.Resilience.ResiliencePolicyReference {{ Name = {FormatStringLiteral(handler.ResiliencePolicyName)} }});");
    }

    private static void AppendIdempotencyDecorator(StringBuilder sb, HandlerInfo handler) {
        if (handler.Idempotent is null)
            return;

        sb.AppendLine($"                handler = new global::Elarion.Abstractions.Idempotency.IdempotencyDecorator<{handler.RequestFqn}, {handler.ResponseFqn}>(");
        sb.AppendLine("                    handler,");
        sb.AppendLine("                    sp.GetRequiredService<global::Elarion.Abstractions.Pipeline.IUnitOfWork>(),");
        sb.AppendLine("                    sp.GetRequiredService<global::Elarion.Abstractions.Idempotency.IIdempotencyStore>(),");
        sb.AppendLine("                    sp.GetRequiredService<global::Elarion.Abstractions.Idempotency.IIdempotencyKeyAccessor>(),");
        sb.AppendLine($"                    new {handler.HandlerName}IdempotencyPolicy(),");
        sb.AppendLine("                    sp.GetRequiredService<global::Elarion.Abstractions.Identity.ICurrentUser>(),");
        sb.AppendLine("                    sp.GetRequiredService<global::Elarion.Abstractions.Serialization.IElarionJsonSerialization>().Options);");
    }

    private static void AppendIdempotencyPolicy(StringBuilder sb, HandlerInfo handler) {
        var info = handler.Idempotent!;

        sb.AppendLine();
        sb.AppendLine($"    private sealed class {handler.HandlerName}IdempotencyPolicy");
        sb.AppendLine($"        : global::Elarion.Abstractions.Idempotency.IIdempotencyPayloadPolicy<{handler.RequestFqn}, {handler.ResponseFqn}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        public global::Elarion.Abstractions.Idempotency.IdempotencyScope Scope => (global::Elarion.Abstractions.Idempotency.IdempotencyScope){info.ScopeValue};");
        sb.AppendLine($"        public bool KeyRequired => {(info.KeyRequired ? "true" : "false")};");
        sb.AppendLine($"        public bool Fingerprint => {(info.Fingerprint ? "true" : "false")};");
        sb.AppendLine($"        public global::Elarion.Abstractions.Idempotency.IdempotencyConflictBehavior ConflictBehavior => (global::Elarion.Abstractions.Idempotency.IdempotencyConflictBehavior){info.ConflictBehaviorValue};");
        sb.AppendLine($"        public global::Elarion.Abstractions.Idempotency.IdempotencyFailureStorage StoreFailures => (global::Elarion.Abstractions.Idempotency.IdempotencyFailureStorage){info.StoreFailuresValue};");
        sb.AppendLine($"        public global::System.TimeSpan Retention => global::System.TimeSpan.FromHours({info.RetentionHours});");
        sb.AppendLine();
        AppendIdempotencyPayloadMethods(sb, handler, info);
        sb.AppendLine("    }");
    }

    private static void AppendIdempotencyPayloadMethods(StringBuilder sb, HandlerInfo handler, IdempotentInfo info) {
        if (info.ResultValueFqn is not null) {
            // Result<T>: store the success value, or (when storing failures) the AppError, so replay reconstructs
            // the exact Result<T>.
            var storedType = $"global::Elarion.Abstractions.Idempotency.StoredResult<{info.ResultValueFqn}>";
            sb.AppendLine($"        public string Serialize({handler.ResponseFqn} response, global::System.Text.Json.JsonSerializerOptions options)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var stored = response.IsSuccess");
            sb.AppendLine($"                ? new {storedType} {{ Ok = true, Value = response.Value }}");
            sb.AppendLine($"                : new {storedType} {{ Ok = false, Error = response.Error }};");
            sb.AppendLine("            return global::System.Text.Json.JsonSerializer.Serialize(stored, options);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        public {handler.ResponseFqn} Deserialize(string payload, global::System.Text.Json.JsonSerializerOptions options)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var stored = global::System.Text.Json.JsonSerializer.Deserialize<{storedType}>(payload, options)!;");
            sb.AppendLine("            return stored.Ok");
            sb.AppendLine($"                ? global::Elarion.Abstractions.Result<{info.ResultValueFqn}>.Success(stored.Value!)");
            sb.AppendLine($"                : global::Elarion.Abstractions.Result<{info.ResultValueFqn}>.Failure(stored.Error ?? global::Elarion.Abstractions.AppError.InternalError);");
            sb.AppendLine("        }");
            return;
        }

        // Non-generic Result response: no value, only success/failure.
        const string nonGenericStored = "global::Elarion.Abstractions.Idempotency.StoredResult";
        sb.AppendLine($"        public string Serialize({handler.ResponseFqn} response, global::System.Text.Json.JsonSerializerOptions options)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var stored = response.IsSuccess");
        sb.AppendLine($"                ? new {nonGenericStored} {{ Ok = true }}");
        sb.AppendLine($"                : new {nonGenericStored} {{ Ok = false, Error = response.Error }};");
        sb.AppendLine("            return global::System.Text.Json.JsonSerializer.Serialize(stored, options);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public {handler.ResponseFqn} Deserialize(string payload, global::System.Text.Json.JsonSerializerOptions options)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var stored = global::System.Text.Json.JsonSerializer.Deserialize<{nonGenericStored}>(payload, options)!;");
        sb.AppendLine("            return stored.Ok");
        sb.AppendLine("                ? global::Elarion.Abstractions.Result.Success()");
        sb.AppendLine("                : global::Elarion.Abstractions.Result.Failure(stored.Error ?? global::Elarion.Abstractions.AppError.InternalError);");
        sb.AppendLine("        }");
    }

    private static void AppendResourceBindingsField(StringBuilder sb, HandlerInfo handler) {
        if (handler.ResourceBindings.IsEmpty)
            return;

        // ADR-0012 Tier 1: each [RequireResource] id path is bound as a generated typed accessor (r => r.Id) —
        // no reflection on the request at run time.
        var bindingType = $"global::Elarion.Abstractions.Authorization.ResourceRequirementBinding<{handler.RequestFqn}>";
        sb.AppendLine($"    private static readonly global::System.Collections.Generic.IReadOnlyList<{bindingType}> __resourceBindings =");
        sb.AppendLine($"        new {bindingType}[]");
        sb.AppendLine("        {");
        foreach (var binding in handler.ResourceBindings.AsImmutableArray) {
            sb.AppendLine(
                $"            new(typeof({binding.ResourceTypeFqn}), new global::Elarion.Abstractions.Authorization.ResourceOperation({FormatStringLiteral(binding.Operation)}), static __r => __r.{binding.IdPath}),");
        }

        sb.AppendLine("        };");
    }

    private static void AppendAuthorizationDecorator(StringBuilder sb, HandlerInfo handler) {
        if (!handler.HasAuthorization)
            return;

        sb.AppendLine($"                handler = new global::Elarion.Abstractions.Authorization.AuthorizationDecorator<{handler.RequestFqn}, {handler.ResponseFqn}>(");
        sb.AppendLine("                    handler,");
        sb.AppendLine("                    __handlerMetadata,");
        sb.Append("                    sp.GetRequiredService<global::Elarion.Abstractions.Authorization.IAuthorizer>()");
        if (handler.RequireAuthenticatedByDefault) {
            sb.Append(",");
            sb.AppendLine();
            sb.Append("                    requireAuthenticatedByDefault: true");
        }

        if (!handler.ResourceBindings.IsEmpty) {
            sb.Append(",");
            sb.AppendLine();
            sb.Append("                    resourceBindings: __resourceBindings");
        }

        sb.AppendLine(");");
    }

    private static void AppendFeatureGateDecorator(StringBuilder sb, HandlerInfo handler) {
        if (!handler.HasFeatureGates)
            return;

        sb.AppendLine($"                handler = new global::Elarion.Abstractions.Features.FeatureGateDecorator<{handler.RequestFqn}, {handler.ResponseFqn}>(");
        sb.AppendLine("                    handler,");
        sb.AppendLine("                    __handlerMetadata,");
        sb.AppendLine("                    sp.GetRequiredService<global::Elarion.Abstractions.Features.IFeatureFlagService>());");
    }

    private static void AppendTracingDecorator(StringBuilder sb, HandlerInfo handler) {
        sb.AppendLine($"                handler = new global::Elarion.Abstractions.Diagnostics.TracingDecorator<{handler.RequestFqn}, {handler.ResponseFqn}>(");
        sb.AppendLine("                    handler,");
        sb.AppendLine($"                    {FormatStringLiteral(handler.HandlerName)});");
    }

    private static void AppendCacheInvalidationDecorator(StringBuilder sb, HandlerInfo handler) {
        if (handler.CacheInvalidation is null)
            return;

        sb.AppendLine($"                handler = new global::Elarion.Abstractions.Caching.CacheInvalidationDecorator<{handler.RequestFqn}, {handler.ResponseFqn}>(");
        sb.AppendLine("                    handler,");
        sb.AppendLine("                    sp.GetRequiredService<global::Elarion.Abstractions.Caching.IHandlerCache>(),");
        sb.AppendLine($"                    new {handler.HandlerName}CacheInvalidationPolicy());");
    }

    private static void AppendCachePolicy(StringBuilder sb, HandlerInfo handler) {
        var cacheable = handler.Cacheable!;

        sb.AppendLine();
        sb.AppendLine($"    private sealed class {handler.HandlerName}CachePolicy");
        sb.AppendLine($"        : global::Elarion.Abstractions.Caching.IHandlerCachePayloadPolicy<{handler.RequestFqn}, {handler.ResponseFqn}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        private static readonly string[] CacheTags = {FormatStringArray(cacheable.Tags)};");
        sb.AppendLine();
        sb.AppendLine($"        public string KeyPrefix => {FormatStringLiteral($"handler-cache:v1:{handler.HandlerFqn}")};");
        sb.AppendLine($"        public global::System.TimeSpan Expiration => global::System.TimeSpan.FromSeconds({cacheable.DurationSeconds});");
        sb.AppendLine($"        public global::Elarion.Abstractions.Caching.HandlerCacheScope Scope => (global::Elarion.Abstractions.Caching.HandlerCacheScope){cacheable.ScopeValue};");
        sb.AppendLine("        public global::System.Collections.Generic.IReadOnlyList<string> Tags => CacheTags;");
        sb.AppendLine();
        AppendCreateKeyMethod(sb, handler.RequestFqn, cacheable.KeyProperties);
        sb.AppendLine();
        AppendPayloadMethods(sb, handler);
        sb.AppendLine("    }");
    }

    private static void AppendCreateKeyMethod(
        StringBuilder sb,
        string requestFqn,
        ImmutableArray<CacheKeyPropertyInfo> keyProperties) {
        sb.AppendLine($"        public string CreateKey({requestFqn} request)");
        sb.AppendLine("        {");

        if (keyProperties.IsEmpty) {
            sb.AppendLine("            return global::Elarion.Abstractions.Caching.HandlerCacheKey.Empty;");
        } else {
            sb.AppendLine("            return global::Elarion.Abstractions.Caching.HandlerCacheKey.Build(");
            for (var i = 0; i < keyProperties.Length; i++) {
                var property = keyProperties[i];
                var comma = i == keyProperties.Length - 1 ? "" : ",";
                sb.AppendLine($"                global::Elarion.Abstractions.Caching.HandlerCacheKey.Part({FormatStringLiteral(property.Name)}, request.{EscapeIdentifier(property.Name)}){comma}");
            }
            sb.AppendLine("            );");
        }

        sb.AppendLine("        }");
    }

    private static void AppendPayloadMethods(StringBuilder sb, HandlerInfo handler) {
        var cacheable = handler.Cacheable!;

        if (cacheable.ResultValueFqn is not null) {
            // Note 59: For Result<T>, only the success value is serialized; failures are handled by the cache layer as non-cacheable.
            sb.AppendLine($"        public string Serialize({handler.ResponseFqn} response, global::System.Text.Json.JsonSerializerOptions options)");
            sb.AppendLine("        {");
            sb.AppendLine("            return global::System.Text.Json.JsonSerializer.Serialize(response.Value, options);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        public {handler.ResponseFqn} Deserialize(string payload, global::System.Text.Json.JsonSerializerOptions options)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var value = global::System.Text.Json.JsonSerializer.Deserialize<{cacheable.ResultValueFqn}>(payload, options);");
            sb.AppendLine($"            return global::Elarion.Abstractions.Result<{cacheable.ResultValueFqn}>.Success(value!);");
            sb.AppendLine("        }");
            return;
        }

        sb.AppendLine($"        public string Serialize({handler.ResponseFqn} response, global::System.Text.Json.JsonSerializerOptions options)");
        sb.AppendLine("        {");
        sb.AppendLine("            return global::System.Text.Json.JsonSerializer.Serialize(response, options);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public {handler.ResponseFqn} Deserialize(string payload, global::System.Text.Json.JsonSerializerOptions options)");
        sb.AppendLine("        {");
        sb.AppendLine($"            return global::System.Text.Json.JsonSerializer.Deserialize<{handler.ResponseFqn}>(payload, options)!;");
        sb.AppendLine("        }");
    }

    private static void AppendCacheInvalidationPolicy(StringBuilder sb, HandlerInfo handler) {
        var invalidation = handler.CacheInvalidation!;

        sb.AppendLine();
        sb.AppendLine($"    private sealed class {handler.HandlerName}CacheInvalidationPolicy");
        sb.AppendLine("        : global::Elarion.Abstractions.Caching.IHandlerCacheInvalidationPolicy");
        sb.AppendLine("    {");
        sb.AppendLine($"        private static readonly string[] CacheTags = {FormatStringArray(invalidation.Tags)};");
        sb.AppendLine();
        sb.AppendLine($"        public global::Elarion.Abstractions.Caching.HandlerCacheScope Scope => (global::Elarion.Abstractions.Caching.HandlerCacheScope){invalidation.ScopeValue};");
        sb.AppendLine("        public global::System.Collections.Generic.IReadOnlyList<string> Tags => CacheTags;");
        sb.AppendLine("    }");
    }

    private static string FormatStringArray(ImmutableArray<string> values) {
        if (values.IsDefaultOrEmpty)
            return "global::System.Array.Empty<string>()";

        return "new[] { " + string.Join(", ", values.Select(FormatStringLiteral)) + " }";
    }

    private static string FormatStringLiteral(string value) =>
        SymbolDisplay.FormatLiteral(value, quote: true);

    private static string EscapeIdentifier(string identifier) =>
        SyntaxFacts.GetKeywordKind(identifier) == SyntaxKind.None
            ? identifier
            : "@" + identifier;
}
