using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Elarion.Generators;

public sealed partial class HandlerRegistrationGenerator {
    private static void EmitHandlerRegistration(SourceProductionContext spc, HandlerInfo handler) {
        foreach (var diagnostic in handler.Diagnostics) {
            spc.ReportDiagnostic(Diagnostic.Create(
                diagnostic.Descriptor,
                diagnostic.Location,
                diagnostic.MessageArgs));
        }

        var code = GenerateRegistration(handler);
        spc.AddSource(GenerateHandlerHintName(handler), SourceText.From(code, Encoding.UTF8));
    }

    private static string GenerateHandlerHintName(HandlerInfo handler) {
        var hintName = handler.HandlerFqn
            .Replace("global::", "")
            .Replace(".", "_")
            .Replace("<", "_")
            .Replace(">", "_")
            .Replace(",", "_")
            .Replace(" ", "");

        return $"{hintName}.g.cs";
    }

    private static string GenerateRegistration(HandlerInfo handler) {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Source: Elarion.Generators.HandlerRegistrationGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"namespace {handler.Namespace};");
        sb.AppendLine();

        sb.AppendLine($"public static class {handler.HandlerName}Registration");
        sb.AppendLine("{");
        AppendAppliesToFields(sb, handler);
        AppendRegistrationMethod(sb, handler);

        if (handler.Cacheable is not null)
            AppendCachePolicy(sb, handler);

        if (handler.CacheInvalidation is not null)
            AppendCacheInvalidationPolicy(sb, handler);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AppendAppliesToFields(StringBuilder sb, HandlerInfo handler) {
        // A decorator with a `public static bool AppliesTo(Type)` predicate is attached conditionally. The
        // predicate is called once here (per closed handler type, at type init) and cached; the factory below
        // reads the cached bool. The call site is a direct static invocation + typeof, so it stays AOT/trim-safe.
        for (var i = 0; i < handler.Decorators.Length; i++) {
            if (!handler.Decorators[i].HasAppliesTo)
                continue;

            sb.AppendLine($"    private static readonly bool __pipelineApplies{i} =");
            sb.AppendLine($"        {handler.Decorators[i].DecoratorFqn}.AppliesTo(typeof({handler.RequestFqn}));");
        }
    }

    private static void AppendRegistrationMethod(StringBuilder sb, HandlerInfo handler) {
        sb.AppendLine($"    public static IServiceCollection Add{handler.HandlerName}(");
        sb.AppendLine("        this IServiceCollection services,");
        sb.AppendLine("        ServiceLifetime lifetime = ServiceLifetime.Scoped)");
        sb.AppendLine("    {");

        // Every handler is registered through the decorator factory because tracing is applied
        // unconditionally as the outermost decorator. The handler span is a no-op until a host
        // registers the Elarion.Handlers source, so there is no plain (undecorated) fast path.
        AppendDecoratedRegistration(sb, handler);

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
    }

    private static void AppendDecoratedRegistration(StringBuilder sb, HandlerInfo handler) {
        sb.AppendLine($"        services.Add(new ServiceDescriptor(typeof({handler.HandlerFqn}), typeof({handler.HandlerFqn}), lifetime));");
        sb.AppendLine("        services.Add(new ServiceDescriptor(");
        sb.AppendLine($"            typeof(global::Elarion.Abstractions.IHandler<{handler.RequestFqn}, {handler.ResponseFqn}>),");
        sb.AppendLine("            sp =>");
        sb.AppendLine("            {");
        // Note 57: The generated factory builds the decorator chain once per DI resolution, preserving normal scoped lifetimes.
        sb.AppendLine($"                global::Elarion.Abstractions.IHandler<{handler.RequestFqn}, {handler.ResponseFqn}> handler =");
        sb.AppendLine($"                    sp.GetRequiredService<{handler.HandlerFqn}>();");

        AppendCacheDecorator(sb, handler);
        AppendPipelineDecorators(sb, handler.Decorators);
        AppendResilienceDecorator(sb, handler);
        AppendCacheInvalidationDecorator(sb, handler);
        // Note: tracing is emitted last so the handler span is the outermost decorator and parents
        // any cache/resilience/pipeline child spans.
        AppendTracingDecorator(sb, handler);

        sb.AppendLine("                return handler;");
        sb.AppendLine("            },");
        sb.AppendLine("            lifetime));");
    }

    private static void AppendCacheDecorator(StringBuilder sb, HandlerInfo handler) {
        if (handler.Cacheable is null)
            return;

        sb.AppendLine($"                handler = new global::Elarion.Abstractions.Caching.CacheDecorator<{handler.RequestFqn}, {handler.ResponseFqn}>(");
        sb.AppendLine("                    handler,");
        sb.AppendLine("                    sp.GetRequiredService<global::Elarion.Abstractions.Caching.IHandlerCache>(),");
        sb.AppendLine($"                    new {handler.HandlerName}CachePolicy());");
    }

    private static void AppendPipelineDecorators(StringBuilder sb, ImmutableArray<DecoratorInfo> decorators) {
        for (var i = decorators.Length - 1; i >= 0; i--) {
            var dec = decorators[i];
            // Note 58: Decorators are emitted in reverse so the first configured decorator becomes the outermost wrapper.
            var indent = "                ";
            if (dec.HasAppliesTo) {
                // Attach only when the decorator's AppliesTo predicate matched this request type (cached above).
                sb.AppendLine($"{indent}if (__pipelineApplies{i})");
                indent += "    ";
            }

            sb.Append($"{indent}handler = new {dec.DecoratorFqn}(handler");
            foreach (var dep in dec.ExtraDependencyFqns) {
                sb.Append($", sp.GetRequiredService<{dep}>()");
            }
            sb.AppendLine(");");
        }
    }

    private static void AppendResilienceDecorator(StringBuilder sb, HandlerInfo handler) {
        if (handler.ResiliencePolicyName is null)
            return;

        sb.AppendLine($"                handler = new global::Elarion.Abstractions.Resilience.ResilienceDecorator<{handler.RequestFqn}, {handler.ResponseFqn}>(");
        sb.AppendLine("                    handler,");
        sb.AppendLine("                    sp.GetRequiredService<global::Elarion.Abstractions.Resilience.IResiliencePipelineRunner>(),");
        sb.AppendLine($"                    new global::Elarion.Abstractions.Resilience.ResiliencePolicyReference {{ Name = {FormatStringLiteral(handler.ResiliencePolicyName)} }});");
    }

    private static void AppendTracingDecorator(StringBuilder sb, HandlerInfo handler) {
        sb.AppendLine($"                handler = new global::Elarion.Abstractions.Diagnostics.TracingDecorator<{handler.RequestFqn}, {handler.ResponseFqn}>(");
        sb.AppendLine("                    handler,");
        sb.AppendLine($"                    {FormatStringLiteral(handler.HandlerName)});");
    }

    private static void AppendCacheInvalidationDecorator(StringBuilder sb, HandlerInfo handler) {
        if (handler.CacheInvalidation is null)
            return;

        sb.AppendLine($"                handler = new global::Elarion.Abstractions.Caching.CacheInvalidationDecorator<{handler.RequestFqn}, {handler.ResponseFqn}>(");
        sb.AppendLine("                    handler,");
        sb.AppendLine("                    sp.GetRequiredService<global::Elarion.Abstractions.Caching.IHandlerCache>(),");
        sb.AppendLine($"                    new {handler.HandlerName}CacheInvalidationPolicy());");
    }

    private static void AppendCachePolicy(StringBuilder sb, HandlerInfo handler) {
        var cacheable = handler.Cacheable!;

        sb.AppendLine();
        sb.AppendLine($"    private sealed class {handler.HandlerName}CachePolicy");
        sb.AppendLine($"        : global::Elarion.Abstractions.Caching.IHandlerCachePayloadPolicy<{handler.RequestFqn}, {handler.ResponseFqn}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        private static readonly string[] CacheTags = {FormatStringArray(cacheable.Tags)};");
        sb.AppendLine();
        sb.AppendLine($"        public string KeyPrefix => {FormatStringLiteral($"handler-cache:v1:{handler.HandlerFqn}")};");
        sb.AppendLine($"        public global::System.TimeSpan Expiration => global::System.TimeSpan.FromSeconds({cacheable.DurationSeconds});");
        sb.AppendLine($"        public global::Elarion.Abstractions.Caching.HandlerCacheScope Scope => (global::Elarion.Abstractions.Caching.HandlerCacheScope){cacheable.ScopeValue};");
        sb.AppendLine("        public global::System.Collections.Generic.IReadOnlyList<string> Tags => CacheTags;");
        sb.AppendLine();
        AppendCreateKeyMethod(sb, handler.RequestFqn, cacheable.KeyProperties);
        sb.AppendLine();
        AppendPayloadMethods(sb, handler);
        sb.AppendLine("    }");
    }

    private static void AppendCreateKeyMethod(
        StringBuilder sb,
        string requestFqn,
        ImmutableArray<CacheKeyPropertyInfo> keyProperties) {
        sb.AppendLine($"        public string CreateKey({requestFqn} request)");
        sb.AppendLine("        {");

        if (keyProperties.IsEmpty) {
            sb.AppendLine("            return global::Elarion.Abstractions.Caching.HandlerCacheKey.Empty;");
        } else {
            sb.AppendLine("            return global::Elarion.Abstractions.Caching.HandlerCacheKey.Build(");
            for (var i = 0; i < keyProperties.Length; i++) {
                var property = keyProperties[i];
                var comma = i == keyProperties.Length - 1 ? "" : ",";
                sb.AppendLine($"                global::Elarion.Abstractions.Caching.HandlerCacheKey.Part({FormatStringLiteral(property.Name)}, request.{EscapeIdentifier(property.Name)}){comma}");
            }
            sb.AppendLine("            );");
        }

        sb.AppendLine("        }");
    }

    private static void AppendPayloadMethods(StringBuilder sb, HandlerInfo handler) {
        var cacheable = handler.Cacheable!;

        if (cacheable.ResultValueFqn is not null) {
            // Note 59: For Result<T>, only the success value is serialized; failures are handled by the cache layer as non-cacheable.
            sb.AppendLine($"        public string Serialize({handler.ResponseFqn} response, global::System.Text.Json.JsonSerializerOptions options)");
            sb.AppendLine("        {");
            sb.AppendLine("            return global::System.Text.Json.JsonSerializer.Serialize(response.Value, options);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        public {handler.ResponseFqn} Deserialize(string payload, global::System.Text.Json.JsonSerializerOptions options)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var value = global::System.Text.Json.JsonSerializer.Deserialize<{cacheable.ResultValueFqn}>(payload, options);");
            sb.AppendLine($"            return global::Elarion.Abstractions.Result<{cacheable.ResultValueFqn}>.Success(value!);");
            sb.AppendLine("        }");
            return;
        }

        sb.AppendLine($"        public string Serialize({handler.ResponseFqn} response, global::System.Text.Json.JsonSerializerOptions options)");
        sb.AppendLine("        {");
        sb.AppendLine("            return global::System.Text.Json.JsonSerializer.Serialize(response, options);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public {handler.ResponseFqn} Deserialize(string payload, global::System.Text.Json.JsonSerializerOptions options)");
        sb.AppendLine("        {");
        sb.AppendLine($"            return global::System.Text.Json.JsonSerializer.Deserialize<{handler.ResponseFqn}>(payload, options)!;");
        sb.AppendLine("        }");
    }

    private static void AppendCacheInvalidationPolicy(StringBuilder sb, HandlerInfo handler) {
        var invalidation = handler.CacheInvalidation!;

        sb.AppendLine();
        sb.AppendLine($"    private sealed class {handler.HandlerName}CacheInvalidationPolicy");
        sb.AppendLine("        : global::Elarion.Abstractions.Caching.IHandlerCacheInvalidationPolicy");
        sb.AppendLine("    {");
        sb.AppendLine($"        private static readonly string[] CacheTags = {FormatStringArray(invalidation.Tags)};");
        sb.AppendLine();
        sb.AppendLine($"        public global::Elarion.Abstractions.Caching.HandlerCacheScope Scope => (global::Elarion.Abstractions.Caching.HandlerCacheScope){invalidation.ScopeValue};");
        sb.AppendLine("        public global::System.Collections.Generic.IReadOnlyList<string> Tags => CacheTags;");
        sb.AppendLine("    }");
    }

    private static string FormatStringArray(ImmutableArray<string> values) {
        if (values.IsDefaultOrEmpty)
            return "global::System.Array.Empty<string>()";

        return "new[] { " + string.Join(", ", values.Select(FormatStringLiteral)) + " }";
    }

    private static string FormatStringLiteral(string value) =>
        SymbolDisplay.FormatLiteral(value, quote: true);

    private static string EscapeIdentifier(string identifier) =>
        SyntaxFacts.GetKeywordKind(identifier) == SyntaxKind.None
            ? identifier
            : "@" + identifier;
}
