using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Elarion.Generators;

/// <summary>
/// Generates the implementing half of a flat <c>MapAll</c> partial method by inspecting referenced assemblies for
/// every class annotated with <c>[Elarion.Abstractions.HttpEndpoint]</c> and emitting a strongly-typed minimal-API
/// <c>MapGet</c>/<c>MapPost</c>/... registration per handler (see <see cref="HttpEndpointEmission"/>).
/// </summary>
/// <remarks>
/// Trigger: annotate the partial class with <c>[Elarion.AspNetCore.GenerateHttpEndpointMap]</c>. This is the
/// <em>non-module</em> path — it maps every discovered handler unconditionally. Module-based hosts instead use the
/// feature-flag-gated mapping emitted by <see cref="AppModuleDiscoveryGenerator"/>.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class HttpEndpointMapGenerator : IIncrementalGenerator
{
    private const string TriggerAttributeMetadataName = "Elarion.AspNetCore.GenerateHttpEndpointMapAttribute";

    private sealed record ClassTarget(string? Namespace, string ClassName);

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                TriggerAttributeMetadataName,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) =>
                {
                    var ns = ctx.TargetSymbol.ContainingNamespace;
                    return new ClassTarget(
                        ns.IsGlobalNamespace ? null : ns.ToDisplayString(),
                        ctx.TargetSymbol.Name);
                });

        var combined = classProvider.Combine(context.CompilationProvider);

        context.RegisterSourceOutput(combined, static (spc, source) =>
        {
            var (target, compilation) = source;
            var entries = HttpEndpointEmission.Collect(compilation, spc.ReportDiagnostic, spc.CancellationToken);

            HttpEndpointEmission.ReportDuplicateRoutes(entries, spc.ReportDiagnostic);

            var code = BuildSource(target, entries);
            spc.AddSource("HttpEndpointMap.g.cs", SourceText.From(code, Encoding.UTF8));
        });
    }

    private static string BuildSource(ClassTarget target, List<HttpEndpointEmission.Model> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Source: Elarion.Generators.HttpEndpointMapGenerator");
        sb.AppendLine("// Do not edit this file manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Elarion.AspNetCore;");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine();

        if (target.Namespace is not null)
        {
            sb.AppendLine($"namespace {target.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public static partial class {target.ClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial IEndpointRouteBuilder MapAll(IEndpointRouteBuilder app)");
        sb.AppendLine("    {");

        foreach (var entry in entries)
            HttpEndpointEmission.AppendRegistration(sb, entry, "        ", "app");

        sb.AppendLine("        return app;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
