using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Elarion.Generators;

/// <summary>
/// Emits the per-module <c>ConfigureDefaultServices</c> aggregation skeleton for every <c>[AppModule]</c> type.
/// <para>
/// For each module it emits a sibling <c>{ModuleType}ElarionModuleServices</c> partial class with a single
/// <c>ConfigureDefaultServices(IServiceCollection)</c> method that invokes one <c>static partial void</c> hook per
/// category (handlers, services, validators, scheduled jobs, event consumers, …). The category generators
/// implement the hooks via filler partials; unimplemented hooks elide to no-ops, so a module that uses only some
/// categories costs nothing for the rest.
/// </para>
/// <para>
/// The skeleton is emitted unconditionally for every <c>[AppModule]</c> (matching the unconditional module manifest),
/// so the host bootstrapper can always call <c>ConfigureDefaultServices</c> gated per module. See
/// <see cref="ModuleDefaultsEmitter"/> for the shared naming and filler contract.
/// </para>
/// <para>
/// This generator also fills the <c>AddJsonTypeInfoResolver</c> hook itself, because the module's JSON context is
/// declared by the module type (a static <c>GetJsonTypeInfoResolver()</c>) rather than by a category generator.
/// That makes module composition self-contained: any container that calls a module's
/// <c>ConfigureDefaultServices</c> gets its source-generated JSON context, without the host-assembly
/// <c>ElarionBootstrapper</c> — the composition a test host cannot reference.
/// </para>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ModuleDefaultServicesGenerator : IIncrementalGenerator {
    private const string AppModuleAttributeMetadataName = "Elarion.Abstractions.Modules.AppModuleAttribute";

    private const string JsonExtensionsFqn =
        "global::Elarion.Abstractions.Serialization.ElarionJsonServiceCollectionExtensions";

    private static class TrackingNames {
        public const string Modules = "ModuleDefaultsModules";
    }

    /// <param name="Namespace">The module type's namespace, or empty for the global namespace.</param>
    /// <param name="TypeName">The module's simple type name (the sibling class name is derived from it).</param>
    /// <param name="TypeFqn">The module's fully-qualified name, used to call its static JSON hook.</param>
    /// <param name="HasGetJsonTypeInfoResolver">Whether the module declares <c>static GetJsonTypeInfoResolver()</c>.</param>
    private sealed record ModuleTarget(
        string Namespace,
        string TypeName,
        string TypeFqn,
        bool HasGetJsonTypeInfoResolver);

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var modules = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AppModuleAttributeMetadataName,
                static (node, _) => node is TypeDeclarationSyntax,
                static (ctx, _) => CreateTarget(ctx))
            .Where(static module => module is not null)
            .Select(static (module, _) => module!)
            .WithTrackingName(TrackingNames.Modules);

        context.RegisterSourceOutput(modules, static (spc, module) => Emit(spc, module));
    }

    private static ModuleTarget? CreateTarget(GeneratorAttributeSyntaxContext ctx) {
        if (ctx.TargetSymbol is not INamedTypeSymbol type)
            return null;

        var ns = type.ContainingNamespace is { IsGlobalNamespace: false } containing
            ? containing.ToDisplayString()
            : string.Empty;
        return new ModuleTarget(
            ns,
            type.Name,
            type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            AppModuleDiscovery.HasStaticMethod(type, "GetJsonTypeInfoResolver", 0));
    }

    private static void Emit(SourceProductionContext spc, ModuleTarget module) {
        EmitSkeleton(spc, module);

        // No filler when the module declares no context: the hook call site elides to a no-op, so a module
        // without JSON types costs nothing and the skeleton still compiles.
        if (!module.HasGetJsonTypeInfoResolver)
            return;

        ModuleDefaultsEmitter.EmitFiller(
            spc,
            module.Namespace,
            module.TypeName,
            ModuleDefaultsEmitter.AddJsonTypeInfoResolverMethod,
            "JsonTypeInfoResolver",
            $"{JsonExtensionsFqn}.ConfigureElarionJson(services, o => o.TypeInfoResolvers.Add({module.TypeFqn}.GetJsonTypeInfoResolver()));");
    }

    private static void EmitSkeleton(SourceProductionContext spc, ModuleTarget module) {
        var className = ModuleDefaultsEmitter.SiblingClassName(module.TypeName);
        var services = ModuleDefaultsEmitter.ServiceCollectionFqn;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Source: Elarion.Generators.ModuleDefaultServicesGenerator");
        sb.AppendLine("// Do not edit this file manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (module.Namespace.Length > 0) {
            sb.AppendLine($"namespace {module.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine("/// <summary>Generated aggregation of the module's default service registrations.</summary>");
        sb.AppendLine($"public static partial class {className}");
        sb.AppendLine("{");
        sb.AppendLine(
            "    /// <summary>Registers all generated default services for this module (handlers, stream handlers, services, validators, scheduled jobs, event consumers) and contributes the module's source-generated JSON context.</summary>");
        sb.AppendLine($"    public static {services} ConfigureDefaultServices({services} services)");
        sb.AppendLine("    {");
        foreach (var method in ModuleDefaultsEmitter.PartialMethods)
            sb.AppendLine($"        {method}(services);");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine();
        foreach (var method in ModuleDefaultsEmitter.PartialMethods)
            sb.AppendLine($"    static partial void {method}({services} services);");
        sb.AppendLine("}");

        spc.AddSource(
            ModuleDefaultsEmitter.HintName(module.Namespace, module.TypeName, "Skeleton"),
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
