using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Elarion.Generators;

/// <summary>
/// Shared emission contract for the per-module <c>ConfigureDefaultServices</c> aggregation.
/// <para>
/// <see cref="ModuleDefaultServicesGenerator"/> emits, per <c>[AppModule]</c>, a sibling
/// <c>{ModuleType}ElarionModuleServices</c> partial class declaring the aggregating method and a
/// <c>static partial void</c> hook per category. Each category generator (handlers, services, validators,
/// scheduled jobs, event consumers) contributes a filler partial that implements its hook. Unimplemented
/// hooks elide to no-ops, so a module without a given category costs nothing and the host call always compiles.
/// </para>
/// <para>
/// The sibling class lives in the module type's namespace and is named by appending <see cref="ClassSuffix"/>
/// to the module's simple type name, so its fully-qualified name is exactly the module's
/// <c>TypeFqn + ClassSuffix</c>. The host bootstrapper relies on that to call <c>ConfigureDefaultServices</c>
/// without any additional manifest metadata.
/// </para>
/// </summary>
internal static class ModuleDefaultsEmitter
{
    public const string ClassSuffix = "ElarionModuleServices";

    public const string AddHandlersMethod = "AddHandlers";
    public const string AddServicesMethod = "AddServices";
    public const string AddVariantServicesMethod = "AddVariantServices";
    public const string AddValidatorsMethod = "AddValidators";
    public const string AddScheduledJobsMethod = "AddScheduledJobs";
    public const string AddEventConsumersMethod = "AddEventConsumers";
    public const string AddAuthorizationPoliciesMethod = "AddAuthorizationPolicies";
    public const string AddModuleApiMethod = "AddModuleApi";

    public const string ServiceCollectionFqn =
        "global::Microsoft.Extensions.DependencyInjection.IServiceCollection";

    /// <summary>The hook methods, in deterministic registration order.</summary>
    public static readonly string[] PartialMethods =
    [
        AddHandlersMethod,
        AddServicesMethod,
        AddVariantServicesMethod,
        AddValidatorsMethod,
        AddScheduledJobsMethod,
        AddEventConsumersMethod,
        AddAuthorizationPoliciesMethod,
        AddModuleApiMethod
    ];

    public static string SiblingClassName(string moduleTypeName) => moduleTypeName + ClassSuffix;

    /// <summary>
    /// Builds a unique, deterministic generator hint name for a contribution to the sibling class,
    /// disambiguated by the module's namespace so two like-named modules in different namespaces never collide.
    /// </summary>
    public static string HintName(string moduleNamespace, string moduleTypeName, string suffix)
    {
        var baseName = moduleNamespace.Length > 0
            ? moduleNamespace + "." + SiblingClassName(moduleTypeName)
            : SiblingClassName(moduleTypeName);
        return Sanitize(baseName) + "." + suffix + ".g.cs";
    }

    /// <summary>
    /// Emits a filler partial that implements a single declared hook with <paramref name="body"/>.
    /// </summary>
    public static void EmitFiller(
        SourceProductionContext spc,
        string moduleNamespace,
        string moduleTypeName,
        string methodName,
        string suffix,
        string body)
    {
        var className = SiblingClassName(moduleTypeName);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Source: Elarion.Generators (ConfigureDefaultServices contribution)");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (moduleNamespace.Length > 0)
        {
            sb.AppendLine($"namespace {moduleNamespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public static partial class {className}");
        sb.AppendLine("{");
        sb.AppendLine($"    static partial void {methodName}({ServiceCollectionFqn} services)");
        sb.AppendLine("    {");
        sb.AppendLine($"        {body}");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource(HintName(moduleNamespace, moduleTypeName, suffix), SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string Sanitize(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var ch in value)
            sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
        return sb.ToString();
    }
}
