using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Elarion.Generators;

/// <summary>
/// Implements <c>[SettingDefinitions]</c> containers (ADR-0078): each <c>[Setting]</c> partial property becomes a
/// <c>SettingDefinition&lt;T&gt;</c> built from the attribute's key and metadata, and the container gains an
/// <c>All</c> list. When the assembly opts in (<c>[UseElarion]</c> / <c>[GenerateSettingDefinitionCatalog]</c>) it
/// also emits <c>ElarionSettingDefinitions.All</c>, aggregating this assembly's containers and the public ones
/// published through the Elarion manifest of referenced assemblies. Duplicate keys (case-insensitive, because keys
/// double as <c>IConfiguration</c> keys) are an error in the declaring assembly.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SettingDefinitionGenerator : IIncrementalGenerator {
    private const string TriggerAttributeMetadataName = "Elarion.Abstractions.Settings.GenerateSettingDefinitionCatalogAttribute";
    private const string DefinitionFqn = "global::Elarion.Abstractions.Settings.SettingDefinition";
    private const string OptionsFqn = "global::Elarion.Abstractions.Settings.SettingDefinitionOptions";
    private const string ListFqn = "global::System.Collections.Generic.IReadOnlyList<" + DefinitionFqn + ">";

    private static class TrackingNames {
        public const string Containers = "SettingContainers";
        public const string CollectedContainers = "SettingContainersCollected";
    }

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var containers = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                SettingDefinitionDiscovery.DefinitionsAttributeMetadataName,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => SettingDefinitionDiscovery.CreateContainer(ctx))
            .Where(static container => container is not null)
            .Select(static (container, _) => container!)
            .WithTrackingName(TrackingNames.Containers);

        context.RegisterSourceOutput(containers, static (spc, container) => EmitContainer(spc, container));

        var collected = containers.Collect()
            .Select(static (items, _) => items
                .OrderBy(static c => c.Fqn, StringComparer.Ordinal)
                .ToEquatableArray())
            .WithTrackingName(TrackingNames.CollectedContainers);

        var trigger = ModuleProviders.HasTrigger(context, TriggerAttributeMetadataName);
        var rootNamespace = context.CompilationProvider
            .Select(static (compilation, _) => compilation.AssemblyName ?? string.Empty)
            .Combine(context.AnalyzerConfigOptionsProvider.Select(static (options, _) =>
                options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns) ? ns : null))
            .Select(static (pair, _) => string.IsNullOrEmpty(pair.Right) ? pair.Left : pair.Right!);
        var manifests = context.MetadataReferencesProvider
            .Select(static (reference, ct) => ElarionManifestReader.Read(reference, ct))
            .Collect();

        context.RegisterSourceOutput(
            collected.Combine(trigger).Combine(rootNamespace).Combine(manifests),
            static (spc, source) => {
                var (((items, hasTrigger), rootNs), manifestResults) = source;
                ReportDuplicateKeys(spc, items);
                if (!hasTrigger) return;

                EmitCatalog(spc, items, rootNs, manifestResults);
            });
    }

    private static void ReportDuplicateKeys(SourceProductionContext spc, EquatableArray<SettingDefinitionDiscovery.Container> containers) {
        var seen = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var container in containers)
        foreach (var setting in container.Settings)
            if (seen.TryGetValue(setting.Key, out _))
                spc.ReportDiagnostic(DiagnosticInfo
                    .Create(SettingDefinitionDiscovery.DuplicateKey, setting.Location, setting.Key).ToDiagnostic());
            else
                seen[setting.Key] = container.Fqn;
    }

    private static void EmitContainer(SourceProductionContext spc, SettingDefinitionDiscovery.Container container) {
        foreach (var diagnostic in container.Diagnostics) spc.ReportDiagnostic(diagnostic.ToDiagnostic());

        if (container.Diagnostics.Any(static d => d.Severity == DiagnosticSeverity.Error) &&
            container.Settings.IsEmpty)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Source: Elarion.Generators.SettingDefinitionGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591 // Generated code is not documented.");
        sb.AppendLine();
        if (container.Namespace.Length > 0) {
            sb.AppendLine($"namespace {container.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"static partial class {container.Name}");
        sb.AppendLine("{");
        foreach (var setting in container.Settings) {
            sb.AppendLine($"    private static readonly {setting.DefinitionTypeFqn} s_{setting.MemberName} =");
            sb.Append($"        new({Literal(setting.Key)}, new {OptionsFqn} {{ Scopes = new string[] {{ ");
            sb.Append(string.Join(", ", setting.Scopes.Select(Literal)));
            sb.Append(" }");
            if (setting.IsSecret) sb.Append(", IsSecret = true");
            if (setting.IsPinnable) sb.Append(", IsPinnable = true");
            if (setting.Description is not null) sb.Append($", Description = {Literal(setting.Description)}");
            sb.Append(" }");
            if (setting.DefaultExpression is not null) sb.Append($", {setting.DefaultExpression}");
            else if (setting.DefaultFactory is not null) sb.Append($", static () => {setting.DefaultFactory}()");
            sb.AppendLine(");");
            sb.AppendLine(
                $"    {setting.Accessibility} static partial {setting.DefinitionTypeFqn} {setting.MemberName} {{ get => s_{setting.MemberName}; }}");
            sb.AppendLine();
        }

        sb.AppendLine("    /// <summary>Every setting definition this container declares.</summary>");
        sb.Append($"    {(container.IsPublic ? "public" : "internal")} static {ListFqn} All => new {DefinitionFqn}[] {{ ");
        sb.Append(string.Join(", ", container.Settings.Select(static s => s.MemberName)));
        sb.AppendLine(" };");
        sb.AppendLine("}");

        spc.AddSource($"SettingDefinitions.{HintNames.Sanitize(container.Fqn)}.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitCatalog(
        SourceProductionContext spc,
        EquatableArray<SettingDefinitionDiscovery.Container> containers,
        string rootNamespace,
        ImmutableArray<ManifestReadResult> manifests) {
        var manifest = ElarionManifest.Data.Combine(manifests.Select(static r => r.Data));
        var references = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var container in containers)
            if (!container.Settings.IsEmpty)
                references.Add(container.Fqn);

        foreach (var entry in manifest.SettingContainers)
            if (entry.IsPublic)
                references.Add(entry.ContainerFqn);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Source: Elarion.Generators.SettingDefinitionGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591 // Generated code is not documented.");
        sb.AppendLine();
        if (rootNamespace.Length > 0) {
            sb.AppendLine($"namespace {rootNamespace};");
            sb.AppendLine();
        }

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Every setting definition this assembly declares or references. Seed the runtime catalog with");
        sb.AppendLine("/// services.AddElarionSettings(o => o.AddDefinitions(ElarionSettingDefinitions.All)).");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static partial class ElarionSettingDefinitions");
        sb.AppendLine("{");
        sb.Append($"    public static {ListFqn} All {{ get; }} = [");
        sb.Append(string.Join(", ", references.Select(static reference => $".. {reference}.All")));
        sb.AppendLine("];");
        sb.AppendLine("}");
        spc.AddSource("ElarionSettingDefinitions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string Literal(string value) {
        return SymbolDisplay.FormatLiteral(value, true);
    }
}
