using System.Reflection;
using AwesomeAssertions;
using Elarion.Generators;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

namespace Elarion.Tests.Generators;

public sealed class ContractSetRegistrationGeneratorTests {
    [Fact]
    public void GenerateContractSet_TwoImplementations_EmitsGoldenSource() {
        var source = CreateSource(
            """
            namespace Sample.Protocol {
                public interface IPacketBinding {
                }

                public sealed class PingBinding : IPacketBinding {
                }

                public sealed class AuthSessionBinding : IPacketBinding {
                }

                public static partial class PacketBindingRegistrations {
                    [Elarion.Abstractions.GenerateContractSetRegistration(typeof(IPacketBinding))]
                    public static partial Microsoft.Extensions.DependencyInjection.IServiceCollection AddPacketBindings(
                        this Microsoft.Extensions.DependencyInjection.IServiceCollection services);
                }
            }
            """);

        var result = Generate(source);
        var generated = GetGeneratedSource(result, "Sample_Protocol_PacketBindingRegistrations_AddPacketBindings.g.cs");

        var expected =
            """
            // <auto-generated/>
            // Source: Elarion.Generators.ContractSetRegistrationGenerator
            #nullable enable

            using Microsoft.Extensions.DependencyInjection;
            using Microsoft.Extensions.DependencyInjection.Extensions;

            namespace Sample.Protocol;

            partial class PacketBindingRegistrations
            {
                public static partial IServiceCollection AddPacketBindings(this IServiceCollection services)
                {
                    services.TryAddEnumerable(ServiceDescriptor.Singleton<global::Sample.Protocol.IPacketBinding, global::Sample.Protocol.AuthSessionBinding>());
                    services.TryAddEnumerable(ServiceDescriptor.Singleton<global::Sample.Protocol.IPacketBinding, global::Sample.Protocol.PingBinding>());
                    return services;
                }
            }

            """;
        Normalize(generated).Should().Be(Normalize(expected));
    }

    [Fact]
    public void GenerateContractSet_ScopeOverride_IsHonored() {
        var source = CreateSource(
            """
            namespace Sample.Protocol {
                public interface ICodec {
                }

                public sealed class JsonCodec : ICodec {
                }

                internal static partial class CodecRegistrations {
                    [Elarion.Abstractions.GenerateContractSetRegistration(
                        typeof(ICodec),
                        Scope = Elarion.Abstractions.ServiceScope.Scoped)]
                    internal static partial Microsoft.Extensions.DependencyInjection.IServiceCollection AddProtocolCodecs(
                        this Microsoft.Extensions.DependencyInjection.IServiceCollection services);
                }
            }
            """);

        var result = Generate(source);
        var generated = GetGeneratedSource(result, "Sample_Protocol_CodecRegistrations_AddProtocolCodecs.g.cs");

        generated.Should().Contain(
            "internal static partial IServiceCollection AddProtocolCodecs(this IServiceCollection services)");
        generated.Should().Contain(
            "services.TryAddEnumerable(ServiceDescriptor.Scoped<global::Sample.Protocol.ICodec, global::Sample.Protocol.JsonCodec>());");
    }

    [Fact]
    public void GenerateContractSet_AbstractClassContract_MatchesThroughBaseChain() {
        var source = CreateSource(
            """
            namespace Sample.Pipeline {
                public abstract class PipelineStage {
                }

                public abstract class BufferedStage : PipelineStage {
                }

                public sealed class CompressionStage : BufferedStage {
                }

                public static partial class PipelineStageRegistrations {
                    [Elarion.Abstractions.GenerateContractSetRegistration(typeof(PipelineStage))]
                    public static partial Microsoft.Extensions.DependencyInjection.IServiceCollection AddPipelineStages(
                        this Microsoft.Extensions.DependencyInjection.IServiceCollection services);
                }
            }
            """);

        var result = Generate(source);
        var generated = GetGeneratedSource(result, "Sample_Pipeline_PipelineStageRegistrations_AddPipelineStages.g.cs");

        generated.Should().Contain(
            "services.TryAddEnumerable(ServiceDescriptor.Singleton<global::Sample.Pipeline.PipelineStage, global::Sample.Pipeline.CompressionStage>());");
        generated.Should().NotContain("BufferedStage>()");
    }

    [Fact]
    public void GenerateContractSet_PartialImplementation_RegistersOnce() {
        var source = CreateSource(
            """
            namespace Sample.Protocol {
                public interface IPacketBinding {
                }

                public sealed partial class PingBinding : IPacketBinding {
                }

                public sealed partial class PingBinding {
                }

                public static partial class PacketBindingRegistrations {
                    [Elarion.Abstractions.GenerateContractSetRegistration(typeof(IPacketBinding))]
                    public static partial Microsoft.Extensions.DependencyInjection.IServiceCollection AddPacketBindings(
                        this Microsoft.Extensions.DependencyInjection.IServiceCollection services);
                }
            }
            """);

        var result = Generate(source);
        var generated = GetGeneratedSource(result, "Sample_Protocol_PacketBindingRegistrations_AddPacketBindings.g.cs");

        var occurrences = generated.Split("PingBinding>());").Length - 1;
        occurrences.Should().Be(1);
    }

    [Fact]
    public void GenerateContractSet_ConcreteClassContract_EmitsInvalidContractDiagnosticAndEmptyBody() {
        var source = CreateSource(
            """
            namespace Sample.Protocol {
                public sealed class NotAContract {
                }

                public static partial class Registrations {
                    [Elarion.Abstractions.GenerateContractSetRegistration(typeof(NotAContract))]
                    public static partial Microsoft.Extensions.DependencyInjection.IServiceCollection AddNotAContracts(
                        this Microsoft.Extensions.DependencyInjection.IServiceCollection services);
                }
            }
            """);

        var result = Generate(source);
        var generated = GetGeneratedSource(result, "Sample_Protocol_Registrations_AddNotAContracts.g.cs");

        result.Diagnostics.Any(d => d.Id == "ELSG014" && d.Severity == DiagnosticSeverity.Error)
            .Should().BeTrue();
        generated.Should().NotContain("TryAddEnumerable");
    }

    [Fact]
    public void GenerateContractSet_OpenGenericContract_EmitsInvalidContractDiagnostic() {
        var source = CreateSource(
            """
            namespace Sample.Protocol {
                public interface IBinding<T> {
                }

                public static partial class Registrations {
                    [Elarion.Abstractions.GenerateContractSetRegistration(typeof(IBinding<>))]
                    public static partial Microsoft.Extensions.DependencyInjection.IServiceCollection AddBindings(
                        this Microsoft.Extensions.DependencyInjection.IServiceCollection services);
                }
            }
            """);

        var result = Generate(source);

        result.Diagnostics.Any(d => d.Id == "ELSG014" && d.Severity == DiagnosticSeverity.Error)
            .Should().BeTrue();
    }

    [Fact]
    public void GenerateContractSet_NoImplementations_WarnsAndEmitsEmptyMethod() {
        var source = CreateSource(
            """
            namespace Sample.Protocol {
                public interface IPacketBinding {
                }

                public static partial class PacketBindingRegistrations {
                    [Elarion.Abstractions.GenerateContractSetRegistration(typeof(IPacketBinding))]
                    public static partial Microsoft.Extensions.DependencyInjection.IServiceCollection AddPacketBindings(
                        this Microsoft.Extensions.DependencyInjection.IServiceCollection services);
                }
            }
            """);

        var result = Generate(source);
        var generated = GetGeneratedSource(result, "Sample_Protocol_PacketBindingRegistrations_AddPacketBindings.g.cs");

        result.Diagnostics.Any(d => d.Id == "ELSG015" && d.Severity == DiagnosticSeverity.Warning)
            .Should().BeTrue();
        generated.Should().Contain("public static partial IServiceCollection AddPacketBindings(this IServiceCollection services)");
        generated.Should().NotContain("TryAddEnumerable");
    }

    [Fact]
    public void GenerateContractSet_DuplicateDeclaration_EmitsDuplicateDiagnosticAndEmptySecondBody() {
        var source = CreateSource(
            """
            namespace Sample.Protocol {
                public interface IPacketBinding {
                }

                public sealed class PingBinding : IPacketBinding {
                }

                public static partial class PacketBindingRegistrations {
                    [Elarion.Abstractions.GenerateContractSetRegistration(typeof(IPacketBinding))]
                    public static partial Microsoft.Extensions.DependencyInjection.IServiceCollection AddPrimary(
                        this Microsoft.Extensions.DependencyInjection.IServiceCollection services);

                    [Elarion.Abstractions.GenerateContractSetRegistration(typeof(IPacketBinding))]
                    public static partial Microsoft.Extensions.DependencyInjection.IServiceCollection AddSecondary(
                        this Microsoft.Extensions.DependencyInjection.IServiceCollection services);
                }
            }
            """);

        var result = Generate(source);
        var primary = GetGeneratedSource(result, "Sample_Protocol_PacketBindingRegistrations_AddPrimary.g.cs");
        var secondary = GetGeneratedSource(result, "Sample_Protocol_PacketBindingRegistrations_AddSecondary.g.cs");

        result.Diagnostics.Any(d => d.Id == "ELSG016" && d.Severity == DiagnosticSeverity.Error)
            .Should().BeTrue();
        primary.Should().Contain("PingBinding>());");
        secondary.Should().NotContain("TryAddEnumerable");
    }

    [Fact]
    public void GenerateContractSet_GenericImplementation_EmitsUnsupportedDiagnostic() {
        var source = CreateSource(
            """
            namespace Sample.Protocol {
                public interface IPacketBinding {
                }

                public sealed class GenericBinding<T> : IPacketBinding {
                }

                public sealed class PingBinding : IPacketBinding {
                }

                public static partial class PacketBindingRegistrations {
                    [Elarion.Abstractions.GenerateContractSetRegistration(typeof(IPacketBinding))]
                    public static partial Microsoft.Extensions.DependencyInjection.IServiceCollection AddPacketBindings(
                        this Microsoft.Extensions.DependencyInjection.IServiceCollection services);
                }
            }
            """);

        var result = Generate(source);
        var generated = GetGeneratedSource(result, "Sample_Protocol_PacketBindingRegistrations_AddPacketBindings.g.cs");

        result.Diagnostics.Any(d => d.Id == "ELSG017" && d.Severity == DiagnosticSeverity.Error)
            .Should().BeTrue();
        generated.Should().Contain("PingBinding>());");
        generated.Should().NotContain("GenericBinding");
    }

    [Fact]
    public void GenerateContractSet_ServiceOverlap_WarnsAndStillRegisters() {
        var source = CreateSource(
            """
            namespace Sample.Protocol {
                public interface IPacketBinding {
                }

                [Elarion.Abstractions.Service]
                public sealed class PingBinding : IPacketBinding {
                }

                public static partial class PacketBindingRegistrations {
                    [Elarion.Abstractions.GenerateContractSetRegistration(typeof(IPacketBinding))]
                    public static partial Microsoft.Extensions.DependencyInjection.IServiceCollection AddPacketBindings(
                        this Microsoft.Extensions.DependencyInjection.IServiceCollection services);
                }
            }
            """);

        var result = Generate(source);
        var generated = GetGeneratedSource(result, "Sample_Protocol_PacketBindingRegistrations_AddPacketBindings.g.cs");

        result.Diagnostics.Any(d => d.Id == "ELSG018" && d.Severity == DiagnosticSeverity.Warning)
            .Should().BeTrue();
        generated.Should().Contain("PingBinding>());");
    }

    [Fact]
    public void GenerateContractSet_ServiceWithOtherContract_DoesNotWarn() {
        var source = CreateSource(
            """
            namespace Sample.Protocol {
                public interface IPacketBinding {
                }

                public interface IDiagnosticsSource {
                }

                [Elarion.Abstractions.Service(typeof(IDiagnosticsSource))]
                public sealed class PingBinding : IPacketBinding, IDiagnosticsSource {
                }

                public static partial class PacketBindingRegistrations {
                    [Elarion.Abstractions.GenerateContractSetRegistration(typeof(IPacketBinding))]
                    public static partial Microsoft.Extensions.DependencyInjection.IServiceCollection AddPacketBindings(
                        this Microsoft.Extensions.DependencyInjection.IServiceCollection services);
                }
            }
            """);

        var result = Generate(source);

        result.Diagnostics.Any(d => d.Id == "ELSG018").Should().BeFalse();
    }

    [Fact]
    public void GenerateContractSet_NonExtensionMethod_EmitsInvalidMethodDiagnostic() {
        var source = CreateSource(
            """
            namespace Sample.Protocol {
                public interface IPacketBinding {
                }

                public static partial class PacketBindingRegistrations {
                    [Elarion.Abstractions.GenerateContractSetRegistration(typeof(IPacketBinding))]
                    public static partial Microsoft.Extensions.DependencyInjection.IServiceCollection AddPacketBindings(
                        Microsoft.Extensions.DependencyInjection.IServiceCollection services);
                }
            }
            """);

        var result = Generate(source, false);

        result.Diagnostics.Any(d => d.Id == "ELSG019" && d.Severity == DiagnosticSeverity.Error)
            .Should().BeTrue();
        result.GeneratedTrees.Should().BeEmpty();
    }

    [Fact]
    public void GenerateContractSet_WrongReturnType_EmitsInvalidMethodDiagnostic() {
        var source = CreateSource(
            """
            namespace Sample.Protocol {
                public interface IPacketBinding {
                }

                public static partial class PacketBindingRegistrations {
                    [Elarion.Abstractions.GenerateContractSetRegistration(typeof(IPacketBinding))]
                    static partial void AddPacketBindings(
                        this Microsoft.Extensions.DependencyInjection.IServiceCollection services);
                }
            }
            """);

        var result = Generate(source, false);

        result.Diagnostics.Any(d => d.Id == "ELSG019" && d.Severity == DiagnosticSeverity.Error)
            .Should().BeTrue();
    }

    [Fact]
    public void GenerateContractSet_IrrelevantEdit_ReusesPipeline() {
        var source = CreateSource(
            """
            namespace Sample.Protocol {
                public interface IPacketBinding {
                }

                public sealed class PingBinding : IPacketBinding {
                }

                public static partial class PacketBindingRegistrations {
                    [Elarion.Abstractions.GenerateContractSetRegistration(typeof(IPacketBinding))]
                    public static partial Microsoft.Extensions.DependencyInjection.IServiceCollection AddPacketBindings(
                        this Microsoft.Extensions.DependencyInjection.IServiceCollection services);
                }
            }
            """);

        GeneratorCacheAssert.ReusesOutputsAfterIrrelevantEdit(
            new ContractSetRegistrationGenerator(),
            source,
            "ContractSetDeclarations",
            "ContractSetMatches",
            "ContractSetCombined");
    }

    [Fact]
    public void GenerateContractSet_UnrelatedFileEdit_ReusesDiscovery() {
        var source = CreateSource(
            """
            namespace Sample.Protocol {
                public interface IPacketBinding {
                }

                public sealed class PingBinding : IPacketBinding {
                }

                public static partial class PacketBindingRegistrations {
                    [Elarion.Abstractions.GenerateContractSetRegistration(typeof(IPacketBinding))]
                    public static partial Microsoft.Extensions.DependencyInjection.IServiceCollection AddPacketBindings(
                        this Microsoft.Extensions.DependencyInjection.IServiceCollection services);
                }
            }
            """);

        GeneratorCacheAssert.ReusesDiscoveryAfterUnrelatedFileEdit(
            new ContractSetRegistrationGenerator(),
            source,
            "ContractSetDeclarations",
            "ContractSetMatches",
            "ContractSetCombined");
    }

    [Fact]
    public void GenerateContractSet_CalledTwice_ResolvesCompleteUnduplicatedSet() {
        var source = CreateSource(
            """
            namespace Sample.Protocol {
                public interface IPacketBinding {
                }

                public sealed class PingBinding : IPacketBinding {
                }

                public sealed class AuthSessionBinding : IPacketBinding {
                }

                public static partial class PacketBindingRegistrations {
                    [Elarion.Abstractions.GenerateContractSetRegistration(typeof(IPacketBinding))]
                    public static partial Microsoft.Extensions.DependencyInjection.IServiceCollection AddPacketBindings(
                        this Microsoft.Extensions.DependencyInjection.IServiceCollection services);
                }
            }
            """);

        var assembly = EmitAndLoad(source);
        var contractType = assembly.GetType("Sample.Protocol.IPacketBinding", throwOnError: true)!;
        var registrationsType = assembly.GetType("Sample.Protocol.PacketBindingRegistrations", throwOnError: true)!;
        var method = registrationsType.GetMethod("AddPacketBindings", BindingFlags.Public | BindingFlags.Static)!;

        var services = new ServiceCollection();
        method.Invoke(null, [services]);
        method.Invoke(null, [services]);

        using var provider = services.BuildServiceProvider();
        var implementations = provider.GetServices(contractType).Select(s => s!.GetType()).ToArray();

        implementations.Should().HaveCount(2);
        implementations.Select(t => t.Name).Should().BeEquivalentTo("PingBinding", "AuthSessionBinding");
    }

    private static string CreateSource(string testSource) {
        return $$"""
                 namespace Elarion.Abstractions {
                     public enum ServiceScope {
                         Scoped = 0,
                         Singleton = 1,
                         Transient = 2
                     }

                     [System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
                     public sealed class GenerateContractSetRegistrationAttribute : System.Attribute {
                         public GenerateContractSetRegistrationAttribute(System.Type contractType) {
                             ContractType = contractType;
                         }

                         public System.Type ContractType { get; }
                         public ServiceScope Scope { get; init; } = ServiceScope.Singleton;
                     }

                     [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
                     public sealed class ServiceAttribute : System.Attribute {
                         public ServiceAttribute(params System.Type[] serviceTypes) {
                         }

                         public ServiceScope Scope { get; init; } = ServiceScope.Scoped;
                     }
                 }

                 {{testSource}}
                 """;
    }

    private static string Normalize(string text) {
        return text.Replace("\r\n", "\n");
    }

    private static GeneratorDriverRunResult Generate(
        string source,
        bool assertGeneratedOutputCompiles = true) {
        var (result, _) = GenerateCore(source, assertGeneratedOutputCompiles);
        return result;
    }

    private static Assembly EmitAndLoad(string source) {
        var (_, outputCompilation) = GenerateCore(source, true);
        using var stream = new MemoryStream();
        var emitResult = outputCompilation.Emit(stream);

        emitResult.Success.Should().BeTrue();
        return Assembly.Load(stream.ToArray());
    }

    private static (GeneratorDriverRunResult Result, Compilation OutputCompilation) GenerateCore(
        string source,
        bool assertGeneratedOutputCompiles) {
        var parseOptions = new CSharpParseOptions(LanguageVersion.Preview);
        var syntaxTree = CSharpSyntaxTree.ParseText(source, parseOptions);
        var compilation = CSharpCompilation.Create(
            "ContractSetRegistrationGeneratorTests",
            [syntaxTree],
            CreateMetadataReferences(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        // CS8795 (partial method lacks an implementation) is expected pre-generation: the generator
        // supplies the implementation part.
        compilation.GetDiagnostics()
            .Where(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error && diagnostic.Id != "CS8795")
            .Should().BeEmpty();

        var driver = CSharpGeneratorDriver
            .Create(new ContractSetRegistrationGenerator())
            .WithUpdatedParseOptions(parseOptions);
        driver = driver.RunGeneratorsAndUpdateCompilation(
            compilation,
            out var outputCompilation,
            out var generatorDiagnostics);
        var result = driver.GetRunResult();

        var unexpectedDiagnostics = generatorDiagnostics.Concat(result.Diagnostics)
            .Where(d => d.Severity == DiagnosticSeverity.Error &&
                        d.Id is not "ELSG014" and not "ELSG016" and not "ELSG017" and not "ELSG019");
        unexpectedDiagnostics.Should().BeEmpty();

        if (assertGeneratedOutputCompiles)
            outputCompilation.GetDiagnostics()
                .Where(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
                .Should().BeEmpty();

        return (result, outputCompilation);
    }

    private static string GetGeneratedSource(GeneratorDriverRunResult result, string fileName) {
        return result.GeneratedTrees
            .Single(tree => string.Equals(Path.GetFileName(tree.FilePath), fileName, StringComparison.Ordinal))
            .GetText()
            .ToString();
    }

    private static IReadOnlyList<MetadataReference> CreateMetadataReferences() {
        var trustedPlatformAssemblies = (string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES");
        trustedPlatformAssemblies.Should().NotBeNull();

        return trustedPlatformAssemblies!
            .Split(Path.PathSeparator)
            .Select(path => MetadataReference.CreateFromFile(path))
            .ToArray();
    }
}
