using AwesomeAssertions;
using Elarion.Generators;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace Elarion.Tests.Generators;

public sealed class ValidationResolverGeneratorTests
{
    private const string Preamble =
        """
        using System.Collections.Generic;
        using System.ComponentModel.DataAnnotations;
        using System.Threading;
        using System.Threading.Tasks;
        using Elarion.Abstractions;
        using Elarion.Abstractions.Modules;
        using Elarion.Abstractions.Results;

        [assembly: UseElarion]
        """;

    [Fact]
    public void AnnotatedRequest_EmitsResolverWithConstantConstructedAttributes()
    {
        const string source = Preamble +
            """

            namespace Sample.App {
                [AppModule("App")]
                public static class AppModule { }

                public sealed record CreateThingCommand : ICommand {
                    [StringLength(100, MinimumLength = 3)]
                    public required string Name { get; init; }

                    [Range(1, 10)]
                    public int Count { get; init; }
                }

                public sealed record CreateThingResponse(string Name);

                public sealed class CreateThingHandler : IHandler<CreateThingCommand, Result<CreateThingResponse>> {
                    public ValueTask<Result<CreateThingResponse>> HandleAsync(CreateThingCommand request, CancellationToken ct) =>
                        ValueTask.FromResult(Result<CreateThingResponse>.Success(new CreateThingResponse("x")));
                }
            }
            """;

        var result = Run(source);
        var generated = GetGenerated(result, "AppValidatableInfoResolver.g.cs");

        generated.Should().Contain(
            "internal sealed class AppValidatableInfoResolver : global::Microsoft.Extensions.Validation.IValidatableInfoResolver");
        generated.Should().Contain("if (type == typeof(global::Sample.App.CreateThingCommand))");
        // Attributes are constant-constructed from compile-time AttributeData — never materialized reflectively.
        generated.Should().Contain(
            "new global::System.ComponentModel.DataAnnotations.StringLengthAttribute(100) { MinimumLength = 3 },");
        generated.Should().Contain("new global::System.ComponentModel.DataAnnotations.RangeAttribute(1, 10),");
        generated.Should().NotContain("GetCustomAttributes");
        generated.Should().StartWith("// <auto-generated/>");
        generated.Should().Contain("#pragma warning disable ASP0029");

        // The module-services hook filler registers the resolver through the gated ConfigureDefaultServices.
        var filler = GetGenerated(result, "Sample_App_AppModuleElarionModuleServices.Validators.g.cs");
        filler.Should().Contain("static partial void AddValidators(");
        filler.Should().Contain(
            "global::Elarion.Validation.ElarionValidationServiceCollectionExtensions.AddElarionValidationResolver(services, new global::Sample.App.AppValidatableInfoResolver());");

        AssertGeneratedOutputCompiles(source);
    }

    [Fact]
    public void AllowedValuesRequest_EmitsConstantConstructedEnumAttribute()
    {
        const string source = Preamble +
            """

            namespace Sample.App {
                [AppModule("App")]
                public static class AppModule { }

                public sealed record SetBackendCommand : ICommand {
                    [AllowedValues("smtp", "office365")]
                    public required string Backend { get; init; }
                }

                public sealed class SetBackendHandler : IHandler<SetBackendCommand, Result<string>> {
                    public ValueTask<Result<string>> HandleAsync(SetBackendCommand request, CancellationToken ct) =>
                        ValueTask.FromResult(Result<string>.Success("ok"));
                }
            }
            """;

        var result = Run(source);
        var generated = GetGenerated(result, "AppValidatableInfoResolver.g.cs");

        // The params object?[] constructor renders as a constant-constructed array — enforcement of the
        // declared value set needs no runtime attribute reflection, like every other mapped constraint.
        generated.Should().Contain("new global::System.ComponentModel.DataAnnotations.AllowedValuesAttribute(");
        generated.Should().Contain("\"smtp\"");
        generated.Should().Contain("\"office365\"");
        generated.Should().NotContain("GetCustomAttributes");

        AssertGeneratedOutputCompiles(source);
    }

    [Fact]
    public void NestedAnnotatedType_RegistersCarrierAndNestedType()
    {
        // The request itself carries no attribute; only the nested type does. The runtime walker recurses into
        // a nested value only when its type resolves through TryGetValidatableTypeInfo, so BOTH the carrier
        // request and the annotated nested type must be registered — and the carrier member must be emitted.
        const string source = Preamble +
            """

            namespace Sample.App {
                [AppModule("App")]
                public static class AppModule { }

                public sealed record RegisterCustomerCommand : ICommand {
                    public required CustomerAddress Address { get; init; }

                    public required IReadOnlyList<CustomerAddress> PreviousAddresses { get; init; }
                }

                public sealed record CustomerAddress {
                    [StringLength(64)]
                    public required string Street { get; init; }
                }

                public sealed class RegisterCustomerHandler : IHandler<RegisterCustomerCommand, Result<Unit>> {
                    public ValueTask<Result<Unit>> HandleAsync(RegisterCustomerCommand request, CancellationToken ct) =>
                        ValueTask.FromResult(Result<Unit>.Success(default));
                }
            }
            """;

        var result = Run(source);
        var generated = GetGenerated(result, "AppValidatableInfoResolver.g.cs");

        generated.Should().Contain("if (type == typeof(global::Sample.App.RegisterCustomerCommand))");
        generated.Should().Contain("if (type == typeof(global::Sample.App.CustomerAddress))");
        generated.Should().Contain(
            "new global::System.ComponentModel.DataAnnotations.StringLengthAttribute(64),");
        // The carrier members recurse without attributes of their own.
        generated.Should().Contain("\"Address\",");
        generated.Should().Contain("\"PreviousAddresses\",");
        generated.Should().Contain("__noAttributes");

        AssertGeneratedOutputCompiles(source);
    }

    [Fact]
    public void PositionalRecordParameterAttributes_AreDiscovered()
    {
        // A positional record's `[StringLength(50)] string Name` lands on the primary-constructor parameter,
        // not the synthesized property — the walker must find it there, like the runtime record handling.
        const string source = Preamble +
            """

            namespace Sample.App {
                [AppModule("App")]
                public static class AppModule { }

                public sealed record RenameThingCommand([StringLength(50)] string Name) : ICommand;

                public sealed class RenameThingHandler : IHandler<RenameThingCommand, Result<Unit>> {
                    public ValueTask<Result<Unit>> HandleAsync(RenameThingCommand request, CancellationToken ct) =>
                        ValueTask.FromResult(Result<Unit>.Success(default));
                }
            }
            """;

        var result = Run(source);
        var generated = GetGenerated(result, "AppValidatableInfoResolver.g.cs");

        generated.Should().Contain("if (type == typeof(global::Sample.App.RenameThingCommand))");
        generated.Should().Contain(
            "new global::System.ComponentModel.DataAnnotations.StringLengthAttribute(50),");

        AssertGeneratedOutputCompiles(source);
    }

    [Fact]
    public void UnannotatedRequest_EmitsNothing()
    {
        const string source = Preamble +
            """

            namespace Sample.App {
                [AppModule("App")]
                public static class AppModule { }

                public sealed record ReadThingQuery(int Id) : IQuery;
                public sealed record ReadThingResponse(string Name);

                public sealed class ReadThingHandler : IHandler<ReadThingQuery, Result<ReadThingResponse>> {
                    public ValueTask<Result<ReadThingResponse>> HandleAsync(ReadThingQuery request, CancellationToken ct) =>
                        ValueTask.FromResult(Result<ReadThingResponse>.Success(new ReadThingResponse("x")));
                }
            }
            """;

        var result = Run(source);

        result.GeneratedTrees.Should().BeEmpty();
        result.Diagnostics.Should().BeEmpty();
    }

    [Fact]
    public void PrefixSiblingNamespace_IsNotAssignedToModule()
    {
        // Regression guard mirroring the module-scoping conventions: 'Sample.Modules.BillingPlus' must not
        // match module 'Sample.Modules.Billing', so its validatable request contributes no resolver entry.
        const string source = Preamble +
            """

            namespace Sample.Modules.Billing {
                [AppModule("Billing")]
                public static class BillingModule { }
            }

            namespace Sample.Modules.BillingPlus {
                public sealed record SiblingCommand : Elarion.Abstractions.ICommand {
                    [System.ComponentModel.DataAnnotations.StringLength(10)]
                    public required string Name { get; init; }
                }

                public sealed class SiblingHandler
                    : Elarion.Abstractions.IHandler<SiblingCommand, Elarion.Abstractions.Result<Elarion.Abstractions.Results.Unit>> {
                    public ValueTask<Elarion.Abstractions.Result<Elarion.Abstractions.Results.Unit>> HandleAsync(
                        SiblingCommand request, CancellationToken ct) =>
                        ValueTask.FromResult(
                            Elarion.Abstractions.Result<Elarion.Abstractions.Results.Unit>.Success(default));
                }
            }
            """;

        var result = Run(source);

        result.GeneratedTrees
            .Any(tree => tree.GetText().ToString().Contains("ValidatableInfoResolver"))
            .Should().BeFalse();
    }

    [Fact]
    public void MissingElarionValidationReference_ReportsElval002AndEmitsNothing()
    {
        const string source = Preamble +
            """

            namespace Sample.App {
                [AppModule("App")]
                public static class AppModule { }

                public sealed record CreateThingCommand : ICommand {
                    [StringLength(100)]
                    public required string Name { get; init; }
                }

                public sealed class CreateThingHandler : IHandler<CreateThingCommand, Result<Unit>> {
                    public ValueTask<Result<Unit>> HandleAsync(CreateThingCommand request, CancellationToken ct) =>
                        ValueTask.FromResult(Result<Unit>.Success(default));
                }
            }
            """;

        var result = Run(source, excludeElarionValidationReference: true);

        // The attributes would flow into every exported schema but nothing would enforce them — that must be
        // a visible choice (ELVAL002), never a silent one.
        result.Diagnostics
            .Any(d => d.Id == "ELVAL002" && d.Severity == DiagnosticSeverity.Warning)
            .Should().BeTrue();
        result.GeneratedTrees.Should().BeEmpty();
    }

    [Fact]
    public void IrrelevantEdit_ReusesPipeline()
    {
        const string source = Preamble +
            """

            namespace Sample.App {
                [AppModule("App")]
                public static class AppModule { }

                public sealed record CreateThingCommand : ICommand {
                    [StringLength(100, MinimumLength = 3)]
                    public required string Name { get; init; }
                }

                public sealed class CreateThingHandler : IHandler<CreateThingCommand, Result<Unit>> {
                    public ValueTask<Result<Unit>> HandleAsync(CreateThingCommand request, CancellationToken ct) =>
                        ValueTask.FromResult(Result<Unit>.Success(default));
                }
            }
            """;

        GeneratorCacheAssert.ReusesOutputsAfterIrrelevantEdit(
            new ValidationResolverGenerator(),
            source,
            "ValidationCandidates",
            "ValidationResolvers",
            "ValidationCombined");
    }

    private static GeneratorDriverRunResult Run(string source, bool excludeElarionValidationReference = false)
    {
        var compilation = CreateCompilation(source, excludeElarionValidationReference);

        GeneratorDriver driver = CSharpGeneratorDriver.Create(new ValidationResolverGenerator());
        driver = driver.RunGenerators(compilation, TestContext.Current.CancellationToken);
        return driver.GetRunResult();
    }

    /// <summary>
    /// The end-to-end compile check: runs the resolver generator together with
    /// <see cref="ModuleDefaultServicesGenerator"/> (which declares the <c>AddValidators</c> hook the filler
    /// implements) and compiles all generated output against the real restored
    /// <c>Microsoft.Extensions.Validation</c>/<c>Elarion.Validation</c> assemblies — so a base-constructor
    /// signature drift in the pinned package version fails this test.
    /// </summary>
    private static void AssertGeneratedOutputCompiles(string source)
    {
        var compilation = CreateCompilation(source, excludeElarionValidationReference: false);

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
                new ValidationResolverGenerator(), new ModuleDefaultServicesGenerator())
            .WithUpdatedParseOptions(new CSharpParseOptions(LanguageVersion.Preview));
        driver.RunGeneratorsAndUpdateCompilation(
            compilation,
            out var outputCompilation,
            out var generatorDiagnostics,
            TestContext.Current.CancellationToken);

        generatorDiagnostics
            .Where(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .Should().BeEmpty();
        outputCompilation.GetDiagnostics(TestContext.Current.CancellationToken)
            .Where(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .Should().BeEmpty();
    }

    private static CSharpCompilation CreateCompilation(string source, bool excludeElarionValidationReference)
    {
        var parseOptions = new CSharpParseOptions(LanguageVersion.Preview);
        var syntaxTree = CSharpSyntaxTree.ParseText(
            source, parseOptions, cancellationToken: TestContext.Current.CancellationToken);
        var compilation = CSharpCompilation.Create(
            "ValidationResolverGeneratorTests",
            [syntaxTree],
            CreateMetadataReferences(excludeElarionValidationReference),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        compilation.GetDiagnostics(TestContext.Current.CancellationToken)
            .Where(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .Should().BeEmpty();

        return compilation;
    }

    private static string GetGenerated(GeneratorDriverRunResult result, string fileName) =>
        result.GeneratedTrees
            .Single(tree => string.Equals(Path.GetFileName(tree.FilePath), fileName, StringComparison.Ordinal))
            .GetText()
            .ToString();

    private static IReadOnlyList<MetadataReference> CreateMetadataReferences(bool excludeElarionValidation)
    {
        var trustedPlatformAssemblies = (string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES");
        trustedPlatformAssemblies.Should().NotBeNull();

        return trustedPlatformAssemblies!
            .Split(Path.PathSeparator)
            .Where(path => !excludeElarionValidation ||
                !string.Equals(Path.GetFileName(path), "Elarion.Validation.dll", StringComparison.OrdinalIgnoreCase))
            .Select(path => MetadataReference.CreateFromFile(path))
            .ToArray();
    }
}
