using System.Collections.Immutable;
using System.Text;
using Elarion.Generators;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Elarion.Sql.Generators;

public sealed partial class SqlRecordMapperGenerator {
    private static void EmitMapper(SourceProductionContext context, SqlRecordModel model, SqlProviderKind provider) {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        if (model.Namespace.Length > 0) {
            builder.Append("namespace ").Append(model.Namespace).AppendLine(";");
            builder.AppendLine();
        }

        var type = model.TypeFqn;
        var columns = model.Columns;

        builder.AppendLine($$"""
            /// <summary>Generated SQL row mapper for <see cref="{{type}}"/> (table "{{model.TableName}}").</summary>
            {{model.Accessibility}} sealed partial class {{model.MapperName}} : global::Elarion.Sql.ISqlRowMapper<{{type}}> {
                /// <summary>The mapped table name.</summary>
                public const string TableName = {{SourceLiterals.String(model.TableName)}};
            """);

        if (model.RequiresJson) {
            builder.AppendLine($$"""

                    private readonly global::Elarion.Abstractions.Serialization.IElarionJsonSerialization? _json;

                    /// <summary>
                    /// JSON columns serialize through the canonical accessor (ADR-0023). The DI registration
                    /// constructs the mapper with it; the static <see cref="Instance"/> reads it lazily from
                    /// the ambient <c>ElarionSqlJson</c> at first JSON-column use (installed at startup).
                    /// </summary>
                    public {{model.MapperName}}(global::Elarion.Abstractions.Serialization.IElarionJsonSerialization json) {
                        _json = json;
                    }

                    private {{model.MapperName}}() {
                    }

                    /// <summary>The shared instance; its JSON accessor comes from the ambient <c>ElarionSqlJson</c>.</summary>
                    public static {{model.MapperName}} Instance { get; } = new {{model.MapperName}}();

                    private global::Elarion.Abstractions.Serialization.IElarionJsonSerialization Json =>
                        _json ?? global::Elarion.Sql.ElarionSqlJson.Serialization;
                """);

            foreach (var column in columns) {
                if (column.Kind != ColumnKind.Json) {
                    continue;
                }

                builder.AppendLine($$"""

                        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<{{column.JsonTypeFqn}}>? _jsonTypeInfo{{column.PropertyName}};

                        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<{{column.JsonTypeFqn}}> JsonTypeInfo{{column.PropertyName}} =>
                            _jsonTypeInfo{{column.PropertyName}} ??= Json.GetTypeInfo<{{column.JsonTypeFqn}}>();
                    """);
            }
        }
        else {
            builder.AppendLine($$"""

                    /// <summary>The shared stateless instance, for DI-free hosts.</summary>
                    public static {{model.MapperName}} Instance { get; } = new {{model.MapperName}}();
                """);
        }

        // Column-name constants: hand-written SQL composes without stringly duplication.
        builder.AppendLine();
        builder.AppendLine("    /// <summary>The mapped column names, for composing hand-written SQL.</summary>");
        builder.AppendLine("    public static class Columns {");
        foreach (var column in columns) {
            builder.AppendLine(
                $"        public const string {column.PropertyName} = {SourceLiterals.String(column.ColumnName)};");
        }

        builder.AppendLine();
        builder.AppendLine("        /// <summary>All mapped columns, comma-separated, in declaration order.</summary>");
        builder.AppendLine(
            $"        public const string All = {SourceLiterals.String(string.Join(", ", columns.Select(static c => c.ColumnName)))};");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>One named placeholder per column, matching <c>BindParameters</c>.</summary>");
        builder.AppendLine(
            $"        public const string AllParameters = {SourceLiterals.String(string.Join(", ", columns.Select(static c => "@" + c.ColumnName)))};");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>The mechanical <c>UPDATE … SET</c> list: every column assigned its placeholder.</summary>");
        builder.AppendLine(
            $"        public const string AllAssignments = {SourceLiterals.String(string.Join(", ", columns.Select(static c => c.ColumnName + " = @" + c.ColumnName)))};");
        builder.AppendLine("    }");

        // Statement constants: only the statements with ZERO query logic — a full-row INSERT and the
        // SELECT-list prefix. Everything with a predicate or clause stays hand-written SQL (ADR-0058);
        // being consts, suffixes compose at compile time ("… ON CONFLICT DO NOTHING", "… WHERE …").
        var insert =
            $"INSERT INTO {model.TableName} ({string.Join(", ", columns.Select(static c => c.ColumnName))}) "
            + $"VALUES ({string.Join(", ", columns.Select(static c => "@" + c.ColumnName))})";
        var select =
            $"SELECT {string.Join(", ", columns.Select(static c => c.ColumnName))} FROM {model.TableName}";
        builder.AppendLine($$"""

                /// <summary>
                /// The full-row INSERT, parameters matching <c>BindParameters</c> — append conflict/returning
                /// clauses as needed (<c>Insert + " ON CONFLICT DO NOTHING"</c>).
                /// </summary>
                public const string Insert = {{SourceLiterals.String(insert)}};

                /// <summary>
                /// The SELECT-list prefix over all mapped columns — append <c>WHERE</c>/<c>ORDER BY</c>/… as
                /// needed; rows read back through the mapper's typed reads.
                /// </summary>
                public const string Select = {{SourceLiterals.String(select)}};
            """);

        // Ordinals: the once-per-result-set name lookup; every row read after it is positional and typed.
        builder.AppendLine();
        builder.AppendLine("    /// <summary>Column ordinals resolved once per result set.</summary>");
        builder.AppendLine("    public readonly struct Ordinals {");
        foreach (var column in columns) {
            builder.AppendLine($"        public readonly int {column.PropertyName};");
        }

        builder.AppendLine();
        builder.AppendLine("        public Ordinals(global::System.Data.Common.DbDataReader reader) {");
        foreach (var column in columns) {
            builder.AppendLine($"            {column.PropertyName} = reader.GetOrdinal(Columns.{column.PropertyName});");
        }

        builder.AppendLine("        }");
        builder.AppendLine("    }");

        builder.AppendLine($$"""

                /// <inheritdoc />
                public {{type}} Read(global::System.Data.Common.DbDataReader reader) => Read(reader, new Ordinals(reader));

                /// <summary>Reads the current row with pre-resolved ordinals — the hot-loop overload.</summary>
                public {{type}} Read(global::System.Data.Common.DbDataReader reader, in Ordinals ordinals) {
            """);
        EmitReadBody(builder, model);
        builder.AppendLine($$"""
                }

                /// <inheritdoc />
                public global::System.Collections.Generic.List<{{type}}> ReadAll(global::System.Data.Common.DbDataReader reader) {
                    var ordinals = new Ordinals(reader);
                    var rows = new global::System.Collections.Generic.List<{{type}}>();
                    while (reader.Read()) {
                        rows.Add(Read(reader, in ordinals));
                    }

                    return rows;
                }

                /// <inheritdoc />
                public async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<{{type}}>> ReadAllAsync(
                    global::System.Data.Common.DbDataReader reader,
                    global::System.Threading.CancellationToken cancellationToken = default) {
                    var ordinals = new Ordinals(reader);
                    var rows = new global::System.Collections.Generic.List<{{type}}>();
                    while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false)) {
                        rows.Add(Read(reader, in ordinals));
                    }

                    return rows;
                }

                /// <inheritdoc />
                public async global::System.Collections.Generic.IAsyncEnumerable<{{type}}> ReadAllStreamAsync(
                    global::System.Data.Common.DbDataReader reader,
                    [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken cancellationToken = default) {
                    var ordinals = new Ordinals(reader);
                    while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false)) {
                        yield return Read(reader, in ordinals);
                    }
                }

                /// <inheritdoc />
                public void BindParameters(global::System.Data.Common.DbCommand command, {{type}} row) {
            """);
        EmitBindBody(builder, model, provider);
        builder.AppendLine("""
                }
            }
            """);

        context.AddSource($"{model.HintName}.SqlMapper.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    // The self-mapping partial (ADR-0058): makes the row type implement ISqlRecord<T> so the query
    // extensions resolve its mapper from the type argument, and exposes Table/Select fragments so
    // hand-written SQL composes without :raw. The row type must be partial (ELSQL010).
    private static void EmitSelfMapping(SourceProductionContext context, SqlRecordModel model) {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        if (model.Namespace.Length > 0) {
            builder.Append("namespace ").Append(model.Namespace).AppendLine(";");
            builder.AppendLine();
        }

        var mapperRef = model.Namespace.Length == 0
            ? "global::" + model.MapperName
            : "global::" + model.Namespace + "." + model.MapperName;

        builder.AppendLine($$"""
            partial {{model.TypeKeyword}} {{model.TypeName}} : global::Elarion.Sql.ISqlRecord<{{model.TypeName}}> {
                /// <summary>The row's generated mapper (a cached singleton).</summary>
                public static global::Elarion.Sql.ISqlRowMapper<{{model.TypeName}}> SqlMapper => {{mapperRef}}.Instance;

                /// <summary>The full-row INSERT command text (backs the insert helpers).</summary>
                public static string InsertCommandText => {{mapperRef}}.Insert;

                /// <summary>The table name as a trusted SQL fragment, for composing hand-written SQL.</summary>
                public static global::Elarion.Sql.SqlStatement Table { get; } =
                    global::Elarion.Sql.SqlStatement.Verbatim({{SourceLiterals.String(model.TableName)}});

                /// <summary>The <c>SELECT</c>-list prefix over all mapped columns, as a trusted SQL fragment.</summary>
                public static global::Elarion.Sql.SqlStatement Select { get; } =
                    global::Elarion.Sql.SqlStatement.Verbatim({{SourceLiterals.String(model.SelectSql)}});
            }
            """);

        context.AddSource($"{model.HintName}.SqlRecord.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private static void EmitReadBody(StringBuilder builder, SqlRecordModel model) {
        var columns = model.Columns;
        var viaCtor = columns.Any(static column => column.CtorPosition >= 0);

        if (!viaCtor) {
            builder.AppendLine($"        return new {model.TypeFqn} {{");
            foreach (var column in columns) {
                builder.AppendLine($"            {column.PropertyName} = {ReadExpression(column)},");
            }

            builder.AppendLine("        };");
            return;
        }

        // Constructor path: read every column into a local first (declaration order — one deterministic
        // read order for both construction styles), then construct.
        foreach (var column in columns) {
            builder.AppendLine($"        var __{column.PropertyName} = {ReadExpression(column)};");
        }

        var arguments = columns
            .Where(static column => column.CtorPosition >= 0)
            .OrderBy(static column => column.CtorPosition)
            .Select(static column => "__" + column.PropertyName);
        builder.Append($"        return new {model.TypeFqn}({string.Join(", ", arguments)})");

        var initialized = columns.Where(static column => column.CtorPosition < 0).ToList();
        if (initialized.Count == 0) {
            builder.AppendLine(";");
            return;
        }

        builder.AppendLine(" {");
        foreach (var column in initialized) {
            builder.AppendLine($"            {column.PropertyName} = __{column.PropertyName},");
        }

        builder.AppendLine("        };");
    }

    private static string ReadExpression(ColumnModel column) {
        var ordinal = $"ordinals.{column.PropertyName}";
        var value = column.Kind switch {
            ColumnKind.Enum =>
                $"({column.EnumTypeFqn})reader.GetFieldValue<{column.ReadTypeFqn}>({ordinal})",
            ColumnKind.Json =>
                $"global::System.Text.Json.JsonSerializer.Deserialize(reader.GetFieldValue<string>({ordinal}), JsonTypeInfo{column.PropertyName})",
            _ => $"reader.GetFieldValue<{column.ReadTypeFqn}>({ordinal})",
        };

        if (column.Kind == ColumnKind.Json && !column.IsNullable) {
            // Deserialize is annotated T?; a non-nullable JSON column trusts the stored document.
            value += "!";
        }

        if (!column.IsNullable) {
            return value;
        }

        var nullValue = column.IsValueType
            ? $"default({(column.Kind == ColumnKind.Enum ? column.EnumTypeFqn : ValueTypeFqn(column))}?)"
            : "null";
        return $"reader.IsDBNull({ordinal}) ? {nullValue} : {value}";

        static string ValueTypeFqn(ColumnModel column) =>
            column.Kind == ColumnKind.Json ? column.JsonTypeFqn! : column.ReadTypeFqn;
    }

    private static void EmitBindBody(StringBuilder builder, SqlRecordModel model, SqlProviderKind provider) {
        builder.AppendLine("        global::System.Data.Common.DbParameter parameter;");
        foreach (var column in model.Columns) {
            builder.AppendLine();
            builder.AppendLine("        parameter = command.CreateParameter();");
            builder.AppendLine($"        parameter.ParameterName = Columns.{column.PropertyName};");
            if (column.Kind == ColumnKind.Json && provider == SqlProviderKind.Npgsql) {
                builder.AppendLine(
                    "        ((global::Npgsql.NpgsqlParameter)parameter).NpgsqlDbType = global::NpgsqlTypes.NpgsqlDbType.Jsonb;");
            }

            builder.AppendLine($"        parameter.Value = {BindExpression(column)};");
            builder.AppendLine("        command.Parameters.Add(parameter);");
        }
    }

    private static string BindExpression(ColumnModel column) {
        var value = "row." + column.PropertyName;
        return column.Kind switch {
            ColumnKind.Json when column.IsNullable && column.IsValueType =>
                $"{value} is null ? (object)global::System.DBNull.Value : global::System.Text.Json.JsonSerializer.Serialize({value}.Value, JsonTypeInfo{column.PropertyName})",
            ColumnKind.Json when column.IsNullable =>
                $"{value} is null ? (object)global::System.DBNull.Value : global::System.Text.Json.JsonSerializer.Serialize({value}, JsonTypeInfo{column.PropertyName})",
            ColumnKind.Json =>
                $"global::System.Text.Json.JsonSerializer.Serialize({value}, JsonTypeInfo{column.PropertyName})",
            ColumnKind.Enum when column.IsNullable =>
                $"{value} is null ? (object)global::System.DBNull.Value : ({column.ReadTypeFqn}){value}.Value",
            ColumnKind.Enum => $"({column.ReadTypeFqn}){value}",
            _ when column.IsNullable => $"(object?){value} ?? global::System.DBNull.Value",
            _ => value,
        };
    }

    private static void EmitRegistration(
        SourceProductionContext context, ImmutableArray<SqlRecordModel?> models, string assemblyName) {
        var mappers = models
            .Where(static model => model is { Emit: true })
            .Select(static model => model!)
            .OrderBy(static model => model.TypeFqn, StringComparer.Ordinal)
            .ToList();
        if (mappers.Count == 0) {
            return;
        }

        var sanitized = Sanitize(assemblyName);
        var builder = new StringBuilder();
        builder.AppendLine($$"""
            // <auto-generated/>
            #nullable enable

            namespace Microsoft.Extensions.DependencyInjection;

            /// <summary>Registers the generated Elarion.Sql row mappers of this assembly as <c>ISqlRowMapper&lt;T&gt;</c> singletons.</summary>
            public static class {{sanitized}}SqlMapperRegistration {
                public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddElarionSqlMappers(
                    this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services) {
            """);
        foreach (var mapper in mappers) {
            var mapperFqn = mapper.Namespace.Length == 0
                ? "global::" + mapper.MapperName
                : "global::" + mapper.Namespace + "." + mapper.MapperName;
            var factory = mapper.RequiresJson
                ? $"static provider => new {mapperFqn}(global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Elarion.Abstractions.Serialization.IElarionJsonSerialization>(provider))"
                : $"static _ => {mapperFqn}.Instance";
            builder.AppendLine(
                $"        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::Elarion.Sql.ISqlRowMapper<{mapper.TypeFqn}>>(services, {factory});");
        }

        // JSON-column mappers self-map through the ambient canonical accessor (their static Instance),
        // so install it at startup — convention over configuration: a JSON-column host wires nothing.
        if (mappers.Any(static m => m.RequiresJson)) {
            builder.AppendLine(
                "        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionHostedServiceExtensions.AddHostedService<global::Elarion.Sql.ElarionSqlJsonInstaller>(services);");
        }

        builder.AppendLine("""
                    return services;
                }
            }
            """);

        context.AddSource("ElarionSqlMapperRegistration.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private static string Sanitize(string assemblyName) {
        var builder = new StringBuilder(assemblyName.Length);
        var upperNext = true;
        foreach (var c in assemblyName) {
            if (char.IsLetterOrDigit(c)) {
                builder.Append(upperNext && char.IsLetter(c) ? char.ToUpperInvariant(c) : c);
                upperNext = false;
            }
            else {
                upperNext = true;
            }
        }

        return builder.Length == 0 ? "Assembly" : builder.ToString();
    }
}
