using System.Collections.Immutable;
using System.Text;
using Elarion.Generators;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Elarion.Idempotency.EntityFrameworkCore.Generators;

/// <summary>
/// Fills every partial <c>DbContext</c> annotated with <c>[GenerateElarionIdempotencyKeys]</c> with the
/// <c>DbSet&lt;IdempotencyKeyEntity&gt;</c> property and an implementation of the EF generator's per-feature
/// model-configuration seam that calls <c>ApplyElarionIdempotencyKeys</c>. So the host writes neither the DbSet
/// nor the table mapping — mirroring <c>[GenerateElarionResourceGrants]</c>/<c>[GenerateElarionIdentity]</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ElarionIdempotencyKeysGenerator : IIncrementalGenerator {
    private const string AttributeMetadataName = "Elarion.Idempotency.EntityFrameworkCore.GenerateElarionIdempotencyKeysAttribute";
    private const string GenerateDbSetsAttributeName = ElarionGeneratorConventions.GenerateDbSetsAttribute;
    private const string IdempotencyNamespace = "global::Elarion.Idempotency.EntityFrameworkCore";

    // The per-feature seam DbContextGenerator declares for this attribute — both sides derive the name from the
    // same convention, so they cannot drift.
    private static readonly string SeamMethodName =
        ElarionGeneratorConventions.ModelConfigurationSeamName("GenerateElarionIdempotencyKeysAttribute");

    private static readonly DiagnosticDescriptor MissingGenerateDbSets = new(
        "ELIDEMEF001",
        "[GenerateElarionIdempotencyKeys] requires [GenerateDbSets]",
        "Context '{0}' is annotated with [GenerateElarionIdempotencyKeys] but not [GenerateDbSets]; add [GenerateDbSets] "
        + "so the idempotency-keys DbSet and model-configuration seam are generated",
        "Elarion.Idempotency.EntityFrameworkCore",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var targets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeMetadataName,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => GetTarget(ctx))
            .Where(static target => target is not null)
            .WithTrackingName("IdempotencyKeysTargets");

        context.RegisterSourceOutput(targets, static (spc, target) => {
            if (target is null) {
                return;
            }

            foreach (var diagnostic in target.Diagnostics) {
                spc.ReportDiagnostic(diagnostic.ToDiagnostic());
            }

            if (target.Emit) {
                Emit(spc, target);
            }
        });
    }

    private sealed record IdempotencyTarget(
        string Namespace,
        string ContextName,
        string HintName,
        bool SnakeCase,
        bool Emit,
        EquatableArray<DiagnosticInfo> Diagnostics);

    private static IdempotencyTarget? GetTarget(GeneratorAttributeSyntaxContext ctx) {
        if (ctx.TargetSymbol is not INamedTypeSymbol contextSymbol) {
            return null;
        }

        var snakeCase = true;
        if (ctx.Attributes.Length > 0) {
            foreach (var namedArgument in ctx.Attributes[0].NamedArguments) {
                if (namedArgument.Key == "SnakeCase" && namedArgument.Value.Value is bool value) {
                    snakeCase = value;
                }
            }
        }

        var fmt = SymbolDisplayFormat.FullyQualifiedFormat;
        var ns = contextSymbol.ContainingNamespace is { IsGlobalNamespace: false } containing
            ? containing.ToDisplayString()
            : "";
        var contextName = contextSymbol.Name;
        var hintName = (ns.Length == 0 ? contextName : ns + "." + contextName).Replace('.', '_');

        var hasGenerateDbSets = contextSymbol.GetAttributes()
            .Any(attribute => attribute.AttributeClass?.ToDisplayString() == GenerateDbSetsAttributeName);

        var diagnostics = ImmutableArray.CreateBuilder<DiagnosticInfo>();
        if (!hasGenerateDbSets) {
            diagnostics.Add(DiagnosticInfo.Create(
                MissingGenerateDbSets, LocationInfo.From(contextSymbol), contextSymbol.ToDisplayString(fmt)));
        }

        return new IdempotencyTarget(
            ns,
            contextName,
            hintName,
            snakeCase,
            Emit: hasGenerateDbSets,
            diagnostics.ToImmutable());
    }

    private static void Emit(SourceProductionContext spc, IdempotencyTarget target) {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Source: Elarion.Idempotency.EntityFrameworkCore.Generators.ElarionIdempotencyKeysGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        if (target.Namespace.Length > 0) {
            sb.AppendLine($"namespace {target.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {target.ContextName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public DbSet<{IdempotencyNamespace}.IdempotencyKeyEntity> IdempotencyKeys => Set<{IdempotencyNamespace}.IdempotencyKeyEntity>();");
        sb.AppendLine();
        sb.AppendLine("    // Implements the per-feature model-configuration seam the EF DbContext generator calls at the");
        sb.AppendLine("    // end of ConfigureEntities, so it composes with [GenerateElarionIdentity]/[GenerateElarionResourceGrants].");
        sb.AppendLine($"    partial void {SeamMethodName}(ModelBuilder modelBuilder) =>");
        sb.AppendLine($"        {IdempotencyNamespace}.IdempotencyModelBuilderExtensions.ApplyElarionIdempotencyKeys(");
        sb.AppendLine($"            modelBuilder, snakeCase: {(target.SnakeCase ? "true" : "false")});");
        sb.AppendLine("}");

        spc.AddSource($"{target.HintName}.ElarionIdempotencyKeys.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
