import {moduleSpecifier} from './rpc-client-source.js'

interface GenerateEventsClientSourceOptions {
  generatedBy: string
  sourceLabel: string
  schemasFileName: string
  /** Sorted topic names from the schema's `events` block. */
  topics: readonly string[]
}

interface TopicTreeNode {
  topic?: string
  children: Map<string, TopicTreeNode>
}

/**
 * Generates the typed client-event subscription client (ADR-0043) from the schema's `events` block: topic
 * literal types, `z.infer` payload types over the Zod payload schemas (emitted into the schemas file), and
 * an `EventSource` wrapper that multiplexes the authorized subscriptions over one connection. Emitted only
 * when the schema declares events, so event-free schemas produce byte-identical output.
 */
export function generateEventsClientSource(options: GenerateEventsClientSourceOptions): string {
  const schemasImport = moduleSpecifier(options.schemasFileName)
  const topicTree = buildTopicTree(options.topics)

  return [
    `// Auto-generated by ${options.generatedBy} — DO NOT EDIT`,
    `// Source: ${options.sourceLabel}`,
    '',
    "import type { z } from 'zod'",
    `import { rpcEventPayloadSchemas } from '${schemasImport}'`,
    '',
    'export type RpcEventTopic = keyof typeof rpcEventPayloadSchemas & string',
    'export type RpcEventPayload<T extends RpcEventTopic> = z.infer<(typeof rpcEventPayloadSchemas)[T]>',
    '',
    '// The structural surface of the platform EventSource this client needs — injectable for tests,',
    '// polyfills, or a withCredentials/auth wrapper.',
    'export interface ElarionEventSourceLike {',
    '  addEventListener(type: string, listener: (event: { readonly data?: unknown }) => void): void',
    '  close(): void',
    '}',
    '',
    'export type ElarionEventSourceFactory = (url: string) => ElarionEventSourceLike',
    '',
    'export interface ElarionEventsOptions {',
    '  readonly url: string | URL',
    '  // Factory over the platform EventSource (defaults to globalThis.EventSource).',
    '  readonly eventSource?: ElarionEventSourceFactory',
    '  // Validate incoming payloads against the generated Zod payload schemas. Defaults to true.',
    '  readonly validateEvents?: boolean',
    '  // Called when an incoming event cannot be parsed or validated; the event is dropped either way.',
    '  readonly onEventError?: (topic: RpcEventTopic, error: unknown) => void',
    '}',
    '',
    'export interface ElarionEventSubscribeOptions {',
    '  // Subscribe the topic within an application-defined resource scope (e.g. "customer:42"); the server',
    '  // authorizes it fail-closed. Omitted, the subscription observes the global scope plus your own user scope.',
    '  readonly resource?: string',
    '}',
    '',
    'export type ElarionEventHandler<T extends RpcEventTopic> = (payload: RpcEventPayload<T>) => void',
    'export type ElarionUnsubscribe = () => void',
    '',
    '// Client events are at-most-once hints: payloads carry ids/refs, and the client converges by re-running',
    '// queries. Treat every onConnected callback (initial connect and every automatic reconnect) as "you may',
    '// have missed events" and re-query — with TanStack Query, invalidate.',
    'export interface ElarionEventsClient {',
    '  subscribe<T extends RpcEventTopic>(topic: T, handler: ElarionEventHandler<T>): ElarionUnsubscribe',
    '  subscribe<T extends RpcEventTopic>(',
    '    topic: T,',
    '    options: ElarionEventSubscribeOptions,',
    '    handler: ElarionEventHandler<T>',
    '  ): ElarionUnsubscribe',
    '  // Fires on the server\'s elarion.connected control event — once per (re)connect.',
    '  onConnected(handler: () => void): ElarionUnsubscribe',
    '  close(): void',
    '}',
    '',
    'export interface ElarionEventTopicApi<T extends RpcEventTopic> {',
    '  subscribe(handler: ElarionEventHandler<T>): ElarionUnsubscribe',
    '  subscribe(options: ElarionEventSubscribeOptions, handler: ElarionEventHandler<T>): ElarionUnsubscribe',
    '}',
    '',
    'export interface ElarionEventsApi {',
    '  readonly $client: ElarionEventsClient',
    ...emitProperties(topicTree, 1),
    '}',
    '',
    'const rpcEventTopicNames = [',
    ...options.topics.map((topic) => `  ${JSON.stringify(topic)},`),
    '] as const satisfies readonly RpcEventTopic[]',
    '',
    "const CONNECTED_EVENT_TYPE = 'elarion.connected'",
    '',
    'interface EventSubscriptionEntry {',
    '  readonly topic: RpcEventTopic',
    '  readonly resource?: string',
    '  readonly handlers: Set<(payload: unknown) => void>',
    '}',
    '',
    'export function createElarionEvents(options: ElarionEventsOptions): ElarionEventsApi {',
    '  const client = createElarionEventsClient(options)',
    '  const topics: Record<string, unknown> = {}',
    '',
    '  for (const topic of rpcEventTopicNames) {',
    '    setTopicPath(topics, topic, {',
    '      subscribe: (',
    '        optionsOrHandler: ElarionEventSubscribeOptions | ElarionEventHandler<typeof topic>,',
    '        maybeHandler?: ElarionEventHandler<typeof topic>',
    '      ) => client.subscribe(topic, optionsOrHandler as ElarionEventSubscribeOptions, maybeHandler as ElarionEventHandler<typeof topic>),',
    '    })',
    '  }',
    '',
    '  return { ...topics, $client: client } as unknown as ElarionEventsApi',
    '}',
    '',
    'export function createElarionEventsClient(options: ElarionEventsOptions): ElarionEventsClient {',
    '  const createSource = options.eventSource ?? defaultEventSourceFactory',
    '  const validateEvents = options.validateEvents ?? true',
    '',
    '  const subscriptions = new Map<string, EventSubscriptionEntry>()',
    '  const connectedHandlers = new Set<() => void>()',
    '  let source: ElarionEventSourceLike | undefined',
    '  let reconnectScheduled = false',
    '  let closed = false',
    '',
    '  // Subscription changes coalesce onto a microtask, so subscribing N topics during setup opens one',
    '  // connection, not N. EventSource cannot change its URL, so a changed subscription set reconnects.',
    '  function scheduleReconnect(): void {',
    '    if (reconnectScheduled || closed) return',
    '    reconnectScheduled = true',
    '    queueMicrotask(() => {',
    '      reconnectScheduled = false',
    '      if (!closed) connect()',
    '    })',
    '  }',
    '',
    '  function connect(): void {',
    '    source?.close()',
    '    source = undefined',
    '    if (subscriptions.size === 0) return',
    '',
    '    const requested = Array.from(subscriptions.values(), (entry) =>',
    '      entry.resource === undefined ? { topic: entry.topic } : { topic: entry.topic, resource: entry.resource }',
    '    ).sort(compareSubscriptions)',
    '',
    '    const next = createSource(appendSubscriptions(String(options.url), requested))',
    '    for (const topic of new Set(Array.from(subscriptions.values(), (entry) => entry.topic))) {',
    '      next.addEventListener(topic, (event) => dispatch(topic, event))',
    '    }',
    '    next.addEventListener(CONNECTED_EVENT_TYPE, () => {',
    '      for (const handler of [...connectedHandlers]) handler()',
    '    })',
    '    source = next',
    '  }',
    '',
    '  function dispatch(topic: RpcEventTopic, event: { readonly data?: unknown }): void {',
    '    let payload: unknown',
    '    try {',
    '      payload = JSON.parse(String(event.data))',
    '      if (validateEvents) {',
    '        payload = rpcEventPayloadSchemas[topic].parse(payload)',
    '      }',
    '    } catch (error) {',
    '      options.onEventError?.(topic, error)',
    '      return',
    '    }',
    '',
    '    // Handlers match by topic only: the server already filters by the connection\'s subscribed scopes,',
    '    // but the wire frame carries no scope — handlers on the same topic see every matching event.',
    '    for (const entry of subscriptions.values()) {',
    '      if (entry.topic !== topic) continue',
    '      for (const handler of [...entry.handlers]) handler(payload)',
    '    }',
    '  }',
    '',
    '  function subscribe<T extends RpcEventTopic>(',
    '    topic: T,',
    '    optionsOrHandler: ElarionEventSubscribeOptions | ElarionEventHandler<T>,',
    '    maybeHandler?: ElarionEventHandler<T>',
    '  ): ElarionUnsubscribe {',
    "    const subscribeOptions = typeof optionsOrHandler === 'function' ? undefined : optionsOrHandler",
    "    const handler = typeof optionsOrHandler === 'function' ? optionsOrHandler : maybeHandler",
    "    if (typeof handler !== 'function') {",
    "      throw new Error('subscribe requires a handler function.')",
    '    }',
    '    if (closed) {',
    "      throw new Error('The events client is closed.')",
    '    }',
    '',
    '    const key = subscriptionKey(topic, subscribeOptions?.resource)',
    '    let entry = subscriptions.get(key)',
    '    if (entry === undefined) {',
    '      entry = { topic, resource: subscribeOptions?.resource, handlers: new Set() }',
    '      subscriptions.set(key, entry)',
    '      scheduleReconnect()',
    '    }',
    '',
    '    // A fresh wrapper per call, so subscribing the same function twice yields two live subscriptions.',
    '    const wrapped = (payload: unknown) => handler(payload as RpcEventPayload<T>)',
    '    entry.handlers.add(wrapped)',
    '    const current = entry',
    '',
    '    let active = true',
    '    return () => {',
    '      if (!active) return',
    '      active = false',
    '      current.handlers.delete(wrapped)',
    '      if (current.handlers.size === 0 && subscriptions.get(key) === current) {',
    '        subscriptions.delete(key)',
    '        scheduleReconnect()',
    '      }',
    '    }',
    '  }',
    '',
    '  return {',
    "    subscribe: subscribe as ElarionEventsClient['subscribe'],",
    '    onConnected(handler: () => void): ElarionUnsubscribe {',
    '      connectedHandlers.add(handler)',
    '      return () => {',
    '        connectedHandlers.delete(handler)',
    '      }',
    '    },',
    '    close(): void {',
    '      closed = true',
    '      source?.close()',
    '      source = undefined',
    '      subscriptions.clear()',
    '      connectedHandlers.clear()',
    '    },',
    '  }',
    '}',
    '',
    'function defaultEventSourceFactory(url: string): ElarionEventSourceLike {',
    '  const ctor = (globalThis as { EventSource?: new (url: string) => ElarionEventSourceLike }).EventSource',
    '  if (!ctor) {',
    "    throw new Error('No EventSource implementation is available. Pass eventSource in createElarionEvents options.')",
    '  }',
    '  return new ctor(url)',
    '}',
    '',
    '// The subscription set travels as one URL-encoded JSON query parameter (EventSource cannot POST), in a',
    '// deterministic order so equal sets produce equal URLs.',
    'function appendSubscriptions(',
    '  url: string,',
    '  requested: readonly { readonly topic: string; readonly resource?: string }[]',
    '): string {',
    "  const separator = url.includes('?') ? '&' : '?'",
    '  return `${url}${separator}subscriptions=${encodeURIComponent(JSON.stringify(requested))}`',
    '}',
    '',
    'function compareSubscriptions(',
    '  left: { readonly topic: string; readonly resource?: string },',
    '  right: { readonly topic: string; readonly resource?: string }',
    '): number {',
    '  if (left.topic !== right.topic) {',
    '    return left.topic < right.topic ? -1 : 1',
    '  }',
    "  const leftResource = left.resource ?? ''",
    "  const rightResource = right.resource ?? ''",
    '  if (leftResource === rightResource) return 0',
    '  return leftResource < rightResource ? -1 : 1',
    '}',
    '',
    'function subscriptionKey(topic: string, resource: string | undefined): string {',
    '  return resource === undefined ? topic : `${topic}\\u0000${resource}`',
    '}',
    '',
    'function setTopicPath(root: Record<string, unknown>, topic: string, value: unknown): void {',
    "  const segments = topic.split('.')",
    '  let node = root',
    '',
    '  for (let index = 0; index < segments.length - 1; index += 1) {',
    '    const segment = segments[index]',
    '    const existing = node[segment]',
    "    if (typeof existing === 'object' && existing !== null) {",
    '      node = existing as Record<string, unknown>',
    '      continue',
    '    }',
    '',
    '    const next: Record<string, unknown> = {}',
    '    node[segment] = next',
    '    node = next',
    '  }',
    '',
    '  node[segments[segments.length - 1] ?? topic] = value',
    '}',
    '',
  ].join('\n')
}

function buildTopicTree(topics: readonly string[]): TopicTreeNode {
  const root = createTopicTreeNode()
  for (const topic of topics) {
    const segments = topic.split('.')
    let node = root
    for (const segment of segments) {
      let child = node.children.get(segment)
      if (!child) {
        child = createTopicTreeNode()
        node.children.set(segment, child)
      }
      node = child
    }

    node.topic = topic
  }

  return root
}

function createTopicTreeNode(): TopicTreeNode {
  return {children: new Map()}
}

function emitProperties(node: TopicTreeNode, indent: number): string[] {
  const pad = '  '.repeat(indent)
  return Array.from(node.children.entries())
    // Code-unit comparison, never localeCompare: output must be byte-identical regardless of host locale.
    .sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0))
    .map(([segment, child]) => `${pad}readonly ${JSON.stringify(segment)}: ${emitNodeType(child, indent)}`)
}

function emitNodeType(node: TopicTreeNode, indent: number): string {
  const childLines = emitProperties(node, indent + 1)
  const childObject = childLines.length === 0
    ? '{}'
    : `{\n${childLines.join('\n')}\n${'  '.repeat(indent)}}`

  if (node.topic && childLines.length > 0) {
    return `ElarionEventTopicApi<${JSON.stringify(node.topic)}> & ${childObject}`
  }

  if (node.topic) {
    return `ElarionEventTopicApi<${JSON.stringify(node.topic)}>`
  }

  return childObject
}
