import { generateEventsClientSource } from './events-client-source.js'
import { jsonSchemaToTypeScript } from './json-schema-to-ts.js'
import { jsonSchemaToZod } from './json-schema-to-zod.js'
import { collectFilePaths, stripNullable, type SchemaContext } from './json-schema.js'
import { generateRpcClientSource } from './rpc-client-source.js'
import { generateSessionClientSource } from './session-client-source.js'
import { generateStartAdapterSource } from './start-adapter-source.js'
import type { GeneratedRpcClientFiles, GenerateRpcClientOptions, JsonSchema, RpcSchema } from './schema.js'

const DEFAULT_GENERATED_BY = 'elarion-jsonrpc-client-generator'
const DEFAULT_SOURCE_LABEL = 'rpc-schema.json'
const DEFAULT_TYPES_FILE = 'rpc-types.ts'
const DEFAULT_SCHEMAS_FILE = 'rpc-schemas.ts'
const DEFAULT_CLIENT_FILE = 'rpc-client.ts'
const DEFAULT_SESSION_CLIENT_FILE = 'session-client.ts'
const DEFAULT_SESSION_OPERATION = 'elarion.session'
const DEFAULT_START_ADAPTER_FILE = 'start-adapter.ts'
const DEFAULT_EVENTS_CLIENT_FILE = 'events-client.ts'

export { UnsupportedJsonSchemaError } from './json-schema.js'
export type { GeneratedRpcClientFiles, GenerateRpcClientOptions, JsonSchema, RpcSchema } from './schema.js'

export function generateRpcClientFiles(
  schema: RpcSchema,
  options: GenerateRpcClientOptions = {}
): GeneratedRpcClientFiles {
  const generatedBy = options.generatedBy ?? DEFAULT_GENERATED_BY
  const sourceLabel = options.sourceLabel ?? DEFAULT_SOURCE_LABEL
  const typesFileName = options.typesFileName ?? DEFAULT_TYPES_FILE
  const schemasFileName = options.schemasFileName ?? DEFAULT_SCHEMAS_FILE
  const clientFileName = options.clientFileName ?? DEFAULT_CLIENT_FILE
  const methods = Object.keys(schema.methods).sort()

  const typesLines: string[] = [
    `// Auto-generated by ${generatedBy} — DO NOT EDIT`,
    `// Source: ${sourceLabel}`,
    '',
    'export interface RpcMethods {',
  ]

  for (const method of methods) {
    const definition = schema.methods[method]
    const paramsType = jsonSchemaToTypeScript(
      stripNullable(definition.params),
      createContext(definition.params, `methods.${method}.params`),
      1
    )
    const resultType = jsonSchemaToTypeScript(
      stripNullable(definition.result),
      createContext(definition.result, `methods.${method}.result`),
      1
    )
    typesLines.push(`  ${JSON.stringify(method)}: {`)
    typesLines.push(`    params: ${paramsType}`)
    typesLines.push(`    result: ${resultType}`)
    typesLines.push('  }')
  }

  typesLines.push('}')
  typesLines.push('')

  const schemasLines: string[] = [
    `// Auto-generated by ${generatedBy} — DO NOT EDIT`,
    `// Source: ${sourceLabel}`,
    '',
    "import { z } from 'zod'",
    '',
    'export const rpcParamsSchemas = {',
  ]

  for (const method of methods) {
    const definition = schema.methods[method]
    const zodSchema = jsonSchemaToZod(
      stripNullable(definition.params),
      createContext(definition.params, `methods.${method}.params`),
      1
    )
    schemasLines.push(`  ${JSON.stringify(method)}: ${zodSchema},`)
  }

  schemasLines.push('} as const')
  schemasLines.push('')
  schemasLines.push('export type RpcParamsSchemas = typeof rpcParamsSchemas')
  schemasLines.push('')
  schemasLines.push('export const rpcResultSchemas = {')

  for (const method of methods) {
    const definition = schema.methods[method]
    const zodSchema = jsonSchemaToZod(
      stripNullable(definition.result),
      createContext(definition.result, `methods.${method}.result`),
      1
    )
    schemasLines.push(`  ${JSON.stringify(method)}: ${zodSchema},`)
  }

  schemasLines.push('} as const')
  schemasLines.push('')
  schemasLines.push('export type RpcResultSchemas = typeof rpcResultSchemas')
  schemasLines.push('')

  // Client-event payload schemas (ADR-0043), emitted only when the schema declares events so event-free
  // schemas keep producing byte-identical output.
  const eventTopics = Object.keys(schema.events ?? {}).sort()
  if (eventTopics.length > 0) {
    schemasLines.push('export const rpcEventPayloadSchemas = {')
    for (const topic of eventTopics) {
      const definition = (schema.events as NonNullable<RpcSchema['events']>)[topic]
      const zodSchema = jsonSchemaToZod(
        stripNullable(definition.payload),
        createContext(definition.payload, `events.${topic}.payload`),
        1
      )
      schemasLines.push(`  ${JSON.stringify(topic)}: ${zodSchema},`)
    }
    schemasLines.push('} as const')
    schemasLines.push('')
    schemasLines.push('export type RpcEventPayloadSchemas = typeof rpcEventPayloadSchemas')
    schemasLines.push('')
  }

  const idempotentMethods = methods.filter((method) => schema.methods[method].idempotent === true)

  // Where each method carries file payloads (x-elarion-file nodes), so the client can convert between
  // native File values and the base64 wire envelope. Methods without files are omitted entirely.
  const paramsFilePaths: Record<string, string[][]> = {}
  const resultFilePaths: Record<string, string[][]> = {}
  for (const method of methods) {
    const definition = schema.methods[method]
    const params = collectFilePaths(
      stripNullable(definition.params),
      createContext(definition.params, `methods.${method}.params`)
    )
    if (params.length > 0) {
      paramsFilePaths[method] = params
    }

    const result = collectFilePaths(
      stripNullable(definition.result),
      createContext(definition.result, `methods.${method}.result`)
    )
    if (result.length > 0) {
      resultFilePaths[method] = result
    }
  }

  const clientSource = generateRpcClientSource({
    generatedBy,
    sourceLabel,
    typesFileName,
    schemasFileName,
    methods,
    idempotentMethods,
    paramsFilePaths,
    resultFilePaths,
  })

  // The client-capability snapshot client + OpenFeature provider (ADR-0030) is emitted only when the host exposes
  // the session operation, so a schema without it produces byte-identical output. The schema's optional
  // `capabilities` vocabulary (ADR-0032) turns the emitted module/flag/permission/role names into typed constants.
  const sessionOperationName = options.sessionOperationName ?? DEFAULT_SESSION_OPERATION
  const sessionClientFileName = options.sessionClientFileName ?? DEFAULT_SESSION_CLIENT_FILE
  const hasSession = Object.prototype.hasOwnProperty.call(schema.methods, sessionOperationName)
  const sessionClientSource = hasSession
    ? generateSessionClientSource({
        generatedBy,
        sourceLabel,
        operationName: sessionOperationName,
        capabilities: schema.capabilities,
      })
    : undefined

  // The typed client-event subscription client (ADR-0043) is emitted only when the schema declares an
  // `events` block, so event-free schemas produce byte-identical output.
  const eventsClientFileName = options.eventsClientFileName ?? DEFAULT_EVENTS_CLIENT_FILE
  const eventsClientSource = eventTopics.length > 0
    ? generateEventsClientSource({
        generatedBy,
        sourceLabel,
        schemasFileName,
        topics: eventTopics,
      })
    : undefined

  // The framework adapter (ADR-boundary: kept opt-in so the core client stays framework-neutral) is emitted only
  // when a framework is requested, so an unopted schema produces byte-identical output.
  const frameworkAdapterFileName = options.frameworkAdapterFileName ?? DEFAULT_START_ADAPTER_FILE
  const frameworkAdapterSource = options.framework === 'tanstack-start'
    ? generateStartAdapterSource({ generatedBy, sourceLabel, clientFileName })
    : undefined

  return {
    methodCount: methods.length,
    typesFileName,
    schemasFileName,
    clientFileName,
    typesSource: typesLines.join('\n'),
    schemasSource: schemasLines.join('\n'),
    clientSource,
    sessionClientFileName: sessionClientSource === undefined ? undefined : sessionClientFileName,
    sessionClientSource,
    frameworkAdapterFileName: frameworkAdapterSource === undefined ? undefined : frameworkAdapterFileName,
    frameworkAdapterSource,
    eventsClientFileName: eventsClientSource === undefined ? undefined : eventsClientFileName,
    eventsClientSource,
  }
}

function createContext(root: JsonSchema, path: string): SchemaContext {
  return {
    root,
    path,
    resolvingRefs: new Set(),
  }
}
