import { jsonSchemaToTypeScript } from './json-schema-to-ts.js'
import { jsonSchemaToZod } from './json-schema-to-zod.js'
import { stripNullable, type SchemaContext } from './json-schema.js'
import { generateRpcClientSource } from './rpc-client-source.js'
import { generateSessionClientSource } from './session-client-source.js'
import type { GeneratedRpcClientFiles, GenerateRpcClientOptions, JsonSchema, RpcSchema } from './schema.js'

const DEFAULT_GENERATED_BY = 'elarion-jsonrpc-client-generator'
const DEFAULT_SOURCE_LABEL = 'rpc-schema.json'
const DEFAULT_TYPES_FILE = 'rpc-types.ts'
const DEFAULT_SCHEMAS_FILE = 'rpc-schemas.ts'
const DEFAULT_CLIENT_FILE = 'rpc-client.ts'
const DEFAULT_SESSION_CLIENT_FILE = 'session-client.ts'
const DEFAULT_SESSION_OPERATION = 'elarion.session'

export { UnsupportedJsonSchemaError } from './json-schema.js'
export type { GeneratedRpcClientFiles, GenerateRpcClientOptions, JsonSchema, RpcSchema } from './schema.js'

export function generateRpcClientFiles(
  schema: RpcSchema,
  options: GenerateRpcClientOptions = {}
): GeneratedRpcClientFiles {
  const generatedBy = options.generatedBy ?? DEFAULT_GENERATED_BY
  const sourceLabel = options.sourceLabel ?? DEFAULT_SOURCE_LABEL
  const typesFileName = options.typesFileName ?? DEFAULT_TYPES_FILE
  const schemasFileName = options.schemasFileName ?? DEFAULT_SCHEMAS_FILE
  const clientFileName = options.clientFileName ?? DEFAULT_CLIENT_FILE
  const methods = Object.keys(schema.methods).sort()

  const typesLines: string[] = [
    `// Auto-generated by ${generatedBy} — DO NOT EDIT`,
    `// Source: ${sourceLabel}`,
    '',
    'export interface RpcMethods {',
  ]

  for (const method of methods) {
    const definition = schema.methods[method]
    const paramsType = jsonSchemaToTypeScript(
      stripNullable(definition.params),
      createContext(definition.params, `methods.${method}.params`),
      1
    )
    const resultType = jsonSchemaToTypeScript(
      stripNullable(definition.result),
      createContext(definition.result, `methods.${method}.result`),
      1
    )
    typesLines.push(`  ${JSON.stringify(method)}: {`)
    typesLines.push(`    params: ${paramsType}`)
    typesLines.push(`    result: ${resultType}`)
    typesLines.push('  }')
  }

  typesLines.push('}')
  typesLines.push('')

  const schemasLines: string[] = [
    `// Auto-generated by ${generatedBy} — DO NOT EDIT`,
    `// Source: ${sourceLabel}`,
    '',
    "import { z } from 'zod'",
    '',
    'export const rpcParamsSchemas = {',
  ]

  for (const method of methods) {
    const definition = schema.methods[method]
    const zodSchema = jsonSchemaToZod(
      stripNullable(definition.params),
      createContext(definition.params, `methods.${method}.params`),
      1
    )
    schemasLines.push(`  ${JSON.stringify(method)}: ${zodSchema},`)
  }

  schemasLines.push('} as const')
  schemasLines.push('')
  schemasLines.push('export type RpcParamsSchemas = typeof rpcParamsSchemas')
  schemasLines.push('')
  schemasLines.push('export const rpcResultSchemas = {')

  for (const method of methods) {
    const definition = schema.methods[method]
    const zodSchema = jsonSchemaToZod(
      stripNullable(definition.result),
      createContext(definition.result, `methods.${method}.result`),
      1
    )
    schemasLines.push(`  ${JSON.stringify(method)}: ${zodSchema},`)
  }

  schemasLines.push('} as const')
  schemasLines.push('')
  schemasLines.push('export type RpcResultSchemas = typeof rpcResultSchemas')
  schemasLines.push('')

  const idempotentMethods = methods.filter((method) => schema.methods[method].idempotent === true)

  const clientSource = generateRpcClientSource({
    generatedBy,
    sourceLabel,
    typesFileName,
    schemasFileName,
    methods,
    idempotentMethods,
  })

  // The client-capability snapshot client + OpenFeature provider (ADR-0020) is emitted only when the host exposes
  // the session operation, so a schema without it produces byte-identical output.
  const sessionOperationName = options.sessionOperationName ?? DEFAULT_SESSION_OPERATION
  const sessionClientFileName = options.sessionClientFileName ?? DEFAULT_SESSION_CLIENT_FILE
  const hasSession = Object.prototype.hasOwnProperty.call(schema.methods, sessionOperationName)
  const sessionClientSource = hasSession
    ? generateSessionClientSource({ generatedBy, sourceLabel, operationName: sessionOperationName })
    : undefined

  return {
    methodCount: methods.length,
    typesFileName,
    schemasFileName,
    clientFileName,
    typesSource: typesLines.join('\n'),
    schemasSource: schemasLines.join('\n'),
    clientSource,
    sessionClientFileName: sessionClientSource === undefined ? undefined : sessionClientFileName,
    sessionClientSource,
  }
}

function createContext(root: JsonSchema, path: string): SchemaContext {
  return {
    root,
    path,
    resolvingRefs: new Set(),
  }
}
