export interface GenerateSessionClientSourceOptions {
  generatedBy: string
  sourceLabel: string
  /** The bus/REST operation name the session snapshot is served under (default `elarion.session`). */
  operationName: string
}

/**
 * Emits a self-contained client for the Elarion client-capability snapshot (ADR-0030): a typed `ClientSnapshot`,
 * synchronous capability accessors, and an `@openfeature/web-sdk`-shaped provider that answers every key from the
 * cached snapshot via the reserved `module.` / `permission.` / `role.` namespaces (a bare key is a flag/variant).
 *
 * The module has **no imports** — it neither depends on the RPC schema's generated dictionary typing nor pins
 * `@openfeature/web-sdk`, so it type-checks and runs in any browser or Node target. The consumer fetches the
 * snapshot through the generated RPC client (`rpc.{operation}(...)`) and hands it to the factory.
 */
export function generateSessionClientSource(options: GenerateSessionClientSourceOptions): string {
  const { generatedBy, sourceLabel, operationName } = options
  return `// Auto-generated by ${generatedBy} — DO NOT EDIT
// Source: ${sourceLabel}
//
// Client-capability snapshot (operation: ${JSON.stringify(operationName)}). Fetch it with the generated RPC client
// and pass it to createSessionCapabilities / createElarionOpenFeatureProvider.

/** The current user's identity and raw grants, as projected into the snapshot. */
export interface ClientSnapshotUser {
  readonly id: string
  readonly email?: string | null
  readonly isAuthenticated: boolean
  readonly roles: readonly string[]
  readonly permissions: readonly string[]
}

/** The client-capability snapshot returned by the ${JSON.stringify(operationName)} operation. */
export interface ClientSnapshot {
  readonly user: ClientSnapshotUser
  readonly modules: Readonly<Record<string, boolean>>
  readonly flags: Readonly<Record<string, boolean>>
  readonly variants: Readonly<Record<string, string>>
}

/** The reserved OpenFeature key namespaces and their typed builders. */
export const Keys = {
  module: (name: string): string => \`module.\${name}\`,
  permission: (permission: string): string => \`permission.\${permission}\`,
  role: (role: string): string => \`role.\${role}\`,
} as const

/** Synchronous, typed accessors over a cached snapshot. */
export class SessionCapabilities {
  constructor(private readonly snapshot: ClientSnapshot) {}

  get user(): ClientSnapshotUser {
    return this.snapshot.user
  }

  isModuleEnabled(name: string): boolean {
    return this.snapshot.modules[name] ?? false
  }

  hasRole(role: string): boolean {
    return this.snapshot.user.roles.includes(role)
  }

  hasPermission(permission: string): boolean {
    return this.snapshot.user.permissions.includes(permission)
  }

  isFlagEnabled(name: string): boolean {
    return this.snapshot.flags[name] ?? false
  }

  getVariant(name: string): string | undefined {
    return this.snapshot.variants[name]
  }

  /** Resolves a reserved-namespace boolean key (the OpenFeature boolean read). */
  resolveBoolean(key: string): boolean {
    if (key.startsWith('module.')) return this.isModuleEnabled(key.slice('module.'.length))
    if (key.startsWith('permission.')) return this.hasPermission(key.slice('permission.'.length))
    if (key.startsWith('role.')) return this.hasRole(key.slice('role.'.length))
    return this.isFlagEnabled(key)
  }
}

export function createSessionCapabilities(snapshot: ClientSnapshot): SessionCapabilities {
  return new SessionCapabilities(snapshot)
}

/** A single flag resolution result (structurally compatible with OpenFeature's ResolutionDetails). */
export interface ResolutionDetails<T> {
  readonly value: T
  readonly variant?: string
  readonly reason: string
}

/**
 * The subset of the \`@openfeature/web-sdk\` Provider surface this snapshot provider implements. Register it with
 * \`OpenFeature.setProvider(provider as unknown as Provider)\` — the static-context (web) paradigm reads
 * synchronously, so module enablement (deployment-scoped, context-invariant) rides the same snapshot.
 */
export interface ElarionWebProvider {
  readonly metadata: { readonly name: string }
  readonly runsOn: 'client'
  resolveBooleanEvaluation(flagKey: string, defaultValue: boolean): ResolutionDetails<boolean>
  resolveStringEvaluation(flagKey: string, defaultValue: string): ResolutionDetails<string>
  resolveNumberEvaluation(flagKey: string, defaultValue: number): ResolutionDetails<number>
  resolveObjectEvaluation<T>(flagKey: string, defaultValue: T): ResolutionDetails<T>
}

const STATIC = 'STATIC'
const DEFAULT = 'DEFAULT'

/**
 * Builds an OpenFeature web-SDK provider hydrated from one session snapshot. Every key resolves from the cache:
 * \`module.{name}\` / \`permission.{p}\` / \`role.{r}\` are booleans, a bare key is a flag (boolean) or a variant
 * (string), and anything else falls back to the default. No network calls — refresh by building a new provider
 * from a freshly fetched snapshot (e.g. on \`onContextChange\`).
 */
export function createElarionOpenFeatureProvider(snapshot: ClientSnapshot): ElarionWebProvider {
  const capabilities = new SessionCapabilities(snapshot)
  return {
    metadata: { name: 'elarion-session' },
    runsOn: 'client',
    resolveBooleanEvaluation(flagKey, defaultValue) {
      if (
        flagKey.startsWith('module.') ||
        flagKey.startsWith('permission.') ||
        flagKey.startsWith('role.')
      ) {
        return { value: capabilities.resolveBoolean(flagKey), reason: STATIC }
      }
      const flag = snapshot.flags[flagKey]
      return flag === undefined ? { value: defaultValue, reason: DEFAULT } : { value: flag, reason: STATIC }
    },
    resolveStringEvaluation(flagKey, defaultValue) {
      const variant = capabilities.getVariant(flagKey)
      return variant === undefined
        ? { value: defaultValue, reason: DEFAULT }
        : { value: variant, variant, reason: STATIC }
    },
    resolveNumberEvaluation(_flagKey, defaultValue) {
      return { value: defaultValue, reason: DEFAULT }
    },
    resolveObjectEvaluation(_flagKey, defaultValue) {
      return { value: defaultValue, reason: DEFAULT }
    },
  }
}
`
}
