import {moduleSpecifier} from './rpc-client-source.js'

export interface GenerateStartAdapterSourceOptions {
  generatedBy: string
  sourceLabel: string
  /** The core client filename the adapter imports from (default `rpc-client.ts`). */
  clientFileName: string
}

/**
 * Emits the opt-in TanStack Start adapter (`start-adapter.ts`), produced only with `--framework tanstack-start`.
 * It forwards incoming request headers (the `cookie` by default, or the configured `forwardHeaders`) to API calls
 * made during SSR. It imports the framework-specific pieces (`@tanstack/react-start`) so the core generated client
 * never does — a non-Start consumer neither installs nor imports this file, keeping the client's framework-neutral
 * boundary.
 */
export function generateStartAdapterSource(options: GenerateStartAdapterSourceOptions): string {
  const clientImport = moduleSpecifier(options.clientFileName)

  return [
    `// Auto-generated by ${options.generatedBy} — DO NOT EDIT`,
    `// Source: ${options.sourceLabel}`,
    '//',
    '// Opt-in TanStack Start adapter (emitted only with `--framework tanstack-start`). Requires the',
    '// `@tanstack/react-start` peer dependency. The core generated client never imports this module, so a',
    '// consumer that does not opt in stays framework-neutral.',
    "import { createIsomorphicFn } from '@tanstack/react-start'",
    "import { getRequestHeader } from '@tanstack/react-start/server'",
    `import { createRpcApi, type RpcApi, type RpcClientOptions, type RpcHeadersInit } from '${clientImport}'`,
    '',
    "// Forwards the named headers of the incoming request during SSR (names are matched case-insensitively and",
    "// emitted lower-case; a header the request does not carry is skipped), and returns nothing in the browser.",
    "// The read is isolated inside `createIsomorphicFn().server(...)` so the TanStack Start compiler strips both",
    "// the read and the `@tanstack/react-start/server` import from the client bundle — a plain import (even one",
    "// behind a `typeof window` guard) would fail `vite build` with `[import-protection] Import denied`.",
    'export const forwardRequestHeaders = createIsomorphicFn()',
    '  .server((names: readonly string[]): RpcHeadersInit => {',
    '    const forwarded: Record<string, string> = {}',
    '    for (const name of names) {',
    '      const value = getRequestHeader(name)',
    '      if (value) {',
    '        forwarded[name.toLowerCase()] = value',
    '      }',
    '    }',
    '    return forwarded',
    '  })',
    '  .client((_names: readonly string[]): RpcHeadersInit => ({}))',
    '',
    "// Forwards the incoming request's `cookie` during SSR so the RPC call runs as the signed-in user.",
    "export const forwardRequestCookie = (): RpcHeadersInit => forwardRequestHeaders(['cookie'])",
    '',
    '/** Options for {@link createStartRpcApi}: the core client options plus the request headers forwarded during SSR. */',
    'export interface StartRpcClientOptions extends RpcClientOptions {',
    '  /**',
    "   * Incoming request headers to forward on every call made during SSR (default `['cookie']`). The list",
    "   * replaces the default, so include `'cookie'` when you still want the session cookie forwarded; an empty",
    '   * list forwards nothing. Forward identity or correlation headers only — never hop-by-hop or',
    '   * framing headers such as `host`, `connection`, or `content-length`.',
    '   */',
    '  readonly forwardHeaders?: readonly string[]',
    '}',
    '',
    '// Turnkey `createRpcApi` for a TanStack Start app: request-scoped header forwarding (the `cookie` by',
    '// default) is pre-wired, and any `headers` you pass are layered on top (yours win on a conflict).',
    '// Everything else in RpcClientOptions (url, fetch, idempotency, instrumentation, …) passes through unchanged.',
    'export function createStartRpcApi(options: StartRpcClientOptions): RpcApi {',
    "  const { forwardHeaders = ['cookie'], headers: provided, ...rest } = options",
    '  return createRpcApi({',
    '    ...rest,',
    '    headers: async (context) => {',
    '      const forwarded = await forwardRequestHeaders(forwardHeaders)',
    "      const extra = typeof provided === 'function' ? await provided(context) : provided",
    '      return { ...toHeaderRecord(forwarded), ...toHeaderRecord(extra) }',
    '    },',
    '  })',
    '}',
    '',
    '// Normalizes any RpcHeadersInit (Headers, record, or entry tuples) to a plain record so the two sources',
    '// can be merged with object spread.',
    'function toHeaderRecord(init: RpcHeadersInit | undefined): Record<string, string> {',
    '  const record: Record<string, string> = {}',
    '  if (!init) {',
    '    return record',
    '  }',
    '  if (init instanceof Headers) {',
    '    init.forEach((value, key) => {',
    '      record[key] = value',
    '    })',
    '    return record',
    '  }',
    '  if (Array.isArray(init)) {',
    '    for (const [key, value] of init) {',
    '      record[key] = value',
    '    }',
    '    return record',
    '  }',
    '  for (const [key, value] of Object.entries(init)) {',
    '    record[key] = value',
    '  }',
    '  return record',
    '}',
    '',
  ].join('\n')
}
