import { moduleSpecifier } from './rpc-client-source.js'

export interface GenerateStartAdapterSourceOptions {
  generatedBy: string
  sourceLabel: string
  /** The core client filename the adapter imports from (default `rpc-client.ts`). */
  clientFileName: string
}

/**
 * Emits the opt-in TanStack Start adapter (`start-adapter.ts`), produced only with `--framework tanstack-start`.
 * It imports the framework-specific pieces (`@tanstack/react-start`) so the core generated client never does —
 * a non-Start consumer neither installs nor imports this file, keeping the client's framework-neutral boundary.
 */
export function generateStartAdapterSource(options: GenerateStartAdapterSourceOptions): string {
  const clientImport = moduleSpecifier(options.clientFileName)

  return [
    `// Auto-generated by ${options.generatedBy} — DO NOT EDIT`,
    `// Source: ${options.sourceLabel}`,
    '//',
    '// Opt-in TanStack Start adapter (emitted only with `--framework tanstack-start`). Requires the',
    '// `@tanstack/react-start` peer dependency. The core generated client never imports this module, so a',
    '// consumer that does not opt in stays framework-neutral.',
    "import { createIsomorphicFn } from '@tanstack/react-start'",
    "import { getRequestHeader } from '@tanstack/react-start/server'",
    `import { createRpcApi, type RpcApi, type RpcClientOptions, type RpcHeadersInit } from '${clientImport}'`,
    '',
    "// Forwards the incoming request's `cookie` during SSR so the RPC call runs as the signed-in user, and",
    '// returns nothing in the browser. The read is isolated inside `createIsomorphicFn().server(...)` so the',
    '// TanStack Start compiler strips both the read and the `@tanstack/react-start/server` import from the',
    '// client bundle — a plain import (even one behind a `typeof window` guard) would fail `vite build` with',
    '// `[import-protection] Import denied`.',
    'export const forwardRequestCookie = createIsomorphicFn()',
    '  .server((): RpcHeadersInit => {',
    "    const cookie = getRequestHeader('cookie')",
    '    return cookie ? { cookie } : {}',
    '  })',
    '  .client((): RpcHeadersInit => ({}))',
    '',
    '// Turnkey `createRpcApi` for a TanStack Start app: request-scoped cookie forwarding is pre-wired, and any',
    '// `headers` you pass are layered on top (yours win on a conflict). Everything else in RpcClientOptions',
    '// (url, fetch, idempotency, instrumentation, …) passes through unchanged.',
    'export function createStartRpcApi(options: RpcClientOptions): RpcApi {',
    '  const provided = options.headers',
    '  return createRpcApi({',
    '    ...options,',
    '    headers: async (context) => {',
    '      const cookie = await forwardRequestCookie()',
    "      const extra = typeof provided === 'function' ? await provided(context) : provided",
    '      return { ...toHeaderRecord(cookie), ...toHeaderRecord(extra) }',
    '    },',
    '  })',
    '}',
    '',
    '// Normalizes any RpcHeadersInit (Headers, record, or entry tuples) to a plain record so the two sources',
    '// can be merged with object spread.',
    'function toHeaderRecord(init: RpcHeadersInit | undefined): Record<string, string> {',
    '  const record: Record<string, string> = {}',
    '  if (!init) {',
    '    return record',
    '  }',
    '  if (init instanceof Headers) {',
    '    init.forEach((value, key) => {',
    '      record[key] = value',
    '    })',
    '    return record',
    '  }',
    '  if (Array.isArray(init)) {',
    '    for (const [key, value] of init) {',
    '      record[key] = value',
    '    }',
    '    return record',
    '  }',
    '  for (const [key, value] of Object.entries(init)) {',
    '    record[key] = value',
    '  }',
    '  return record',
    '}',
    '',
  ].join('\n')
}
