namespace Elarion.AspNetCore;

/// <summary>
/// Marks a partial class to have its <c>MapAll</c> method body generated by
/// <c>Elarion.Generators.HttpEndpointMapGenerator</c>. Apply to the partial class that declares the
/// <c>MapAll</c> method stub; the generator emits one minimal-API endpoint registration per discovered
/// <c>[Elarion.Abstractions.HttpEndpoint]</c> handler.
/// </summary>
/// <example>
/// <code>
/// [GenerateHttpEndpointMap]
/// public static partial class HttpEndpointMap {
///     public static partial IEndpointRouteBuilder MapAll(IEndpointRouteBuilder app);
/// }
/// </code>
/// </example>
[AttributeUsage(AttributeTargets.Class)]
public sealed class GenerateHttpEndpointMapAttribute : Attribute;
